"""
maps/context.py
===============
Maps structural and situational context signals into normalized English
travel intent keywords for BGE-M3 embedding.

These signals are extracted from short, free-form user input and expanded
into lightweight semantic hints that guide retrieval. They do NOT enforce
hard constraints (e.g. exact duration or distance), but instead provide
soft bias toward travel style, proximity, and budget.

The goal is to enrich sparse queries with consistent, embedding-friendly
tokens such as "travel", "experience", and "activities", improving
semantic matching against destination data.

Duplicate and substring keys are intentional — longer phrases carry
stronger, more specific signals and produce better embedding alignment.

─────────────────────────────────────────────────────────────
SECTION INDEX
─────────────────────────────────────────────────────────────
  A. SEASON & WEATHER       — climate, timing, seasonal context
  B. SOCIAL GROUP           — travel companions and group dynamics
  C. TRIP DURATION          — trip length intent (short vs long)
  D. TRIP DISTANCE          — proximity intent (nearby vs far)
  E. BUDGET LEVEL           — price sensitivity (budget to luxury)
  F. PACE & STYLE           — travel style, flexibility, activity level
  G. NATURE & LANDSCAPE     — terrain, ecosystems, natural features
  H. TRAVEL INTENT          — wanting to go, explore, discover
  I. MOOD & ATMOSPHERE      — vibe, ambience, energy level
  J. ACTIVITIES             — sports, experiences, things to do
  K. FOOD & DRINK           — culinary context signals
  L. ACCOMMODATION          — stay type preferences
  M. CULTURAL & HERITAGE    — history, tradition, local culture
  N. WELLNESS & HEALTH      — spa, healing, mindfulness context
  O. PHOTOGRAPHY & CONTENT  — visual, scenic, instagram signals

"""

# ═════════════════════════════════════════════════════════════
# A. SEASON & WEATHER
# ═════════════════════════════════════════════════════════════
SEASON_WEATHER: dict[str, str] = {
    # ── Vietnamese — seasons ────────────────────────────────
    "mùa hè":               "summer beach coastal travel swimming water activities sun outdoor relaxation",
    "mùa hè này":           "summer beach coastal travel swimming water activities sun outdoor relaxation",
    "đi mùa hè":            "summer beach coastal travel swimming water activities sun outdoor relaxation",
    "mùa đông":             "winter mountain highland travel cool weather cozy indoor retreat scenic nature",
    "mùa đông này":         "winter mountain highland travel cool weather cozy indoor retreat scenic nature",
    "đi mùa đông":          "winter mountain highland cool weather cozy retreat scenic nature travel",
    "mùa xuân":             "spring blossom festival travel fresh air outdoor walking cultural experience",
    "mùa xuân này":         "spring blossom festival travel fresh air outdoor walking cultural experience",
    "mùa thu":              "autumn scenic landscape colorful leaves mountain highland peaceful travel photography",
    "mùa thu này":          "autumn scenic landscape colorful leaves mountain highland peaceful travel photography",
    "mùa khô":              "dry season beach outdoor travel activities sun clear sky coastal exploration",
    "mùa mưa":              "rainy season waterfall green lush cave indoor cozy nature travel",
    "lễ hội":               "festival cultural travel celebration local tradition event experience",
    "dịp lễ hội":           "festival cultural travel celebration local tradition community event",

    # ── Vietnamese — weather ────────────────────────────────
    "nắng":                 "sunny weather beach outdoor travel activities sightseeing clear sky",
    "trời nắng":            "sunny clear sky beach outdoor travel activities sightseeing",
    "trời nắng đẹp":        "beautiful sunny weather beach outdoor travel scenic photography",
    "mưa":                  "rainy weather indoor cafe relaxation waterfall cave nature lush scenery travel",
    "trời mưa":             "rainy indoor cozy cafe waterfall cave nature lush travel",
    "nóng":                 "hot weather cooling beach water swimming highland escape travel",
    "trời nóng":            "hot weather cooling beach water swimming highland escape travel",
    "lạnh":                 "cold weather warm indoor cozy mountain retreat scenic travel",
    "trời lạnh":            "cold weather warm indoor cozy mountain retreat scenic travel",
    "hanh":                 "dry weather beach outdoor travel clear sky activities sunshine",
    "oi":                   "humid hot weather coastal breeze beach water highland cooling travel",
    "oi bức":               "humid hot weather coastal breeze beach water swimming highland escape",
    "sương":                "misty weather highland mountain foggy atmospheric scenic travel photography",
    "sương mù":             "misty foggy highland mountain atmospheric ethereal scenic travel photography",
    "gió":                  "windy coastal beach open space fresh air outdoor travel scenic",
    "có gió":               "windy coastal beach fresh air outdoor travel scenic relaxed",
    "bão":                  "storm weather indoor shelter safe travel cave highland dramatic scenery",
    "tuyết":                "snow winter mountain highland scenic travel cold weather cozy retreat",
    "có tuyết":             "snowy winter mountain highland scenic travel cold cozy retreat",
    "sấm":                  "thunder storm indoor cozy shelter travel dramatic cave highland",
    "mát mẻ":               "cool weather highland mountain fresh air forest nature travel relaxation",
    "thời tiết mát":        "cool pleasant weather highland mountain fresh air nature travel",
    "thời tiết mát mẻ":     "cool pleasant weather highland mountain fresh air forest nature travel",
    "trời đẹp":             "beautiful weather sunny outdoor travel scenic beach picnic clear sky",
    "thời tiết đẹp":        "beautiful weather sunny outdoor travel scenic beach picnic clear sky photography",
    "dễ chịu":              "pleasant weather outdoor travel gentle walking nature relaxation",
    "thời tiết dễ chịu":    "pleasant mild weather outdoor travel gentle walking nature relaxation",
    "khí hậu mát":          "cool climate highland mountain fresh air forest travel",
    "khí hậu mát mẻ":       "cool pleasant climate highland mountain fresh air forest nature travel",
    "trời rét":             "cold weather warm indoor cozy mountain travel",
    "rét":                  "cold chilly weather warm indoor cozy mountain travel",
    "ẩm thấp":              "humid wet weather indoor cave waterfall lush travel",
    "trời trong":           "clear sky sunny outdoor travel scenic beach nature",
    "mùa ẩm":               "wet season rainy waterfall cave lush nature travel",
    "nhiệt độ cao":         "hot weather cooling beach water coastal highland travel",
    "nhiệt độ thấp":        "cold weather warm indoor mountain highland retreat travel",
    "nắng nóng":            "hot sunny weather beach water cooling highland travel escape",

    # ── Vietnamese — timing / occasion ─────────────────────
    "cuối tuần":            "weekend short trip nearby travel quick getaway relaxation",
    "cuối tuần này":        "weekend short trip nearby travel quick getaway relaxation",
    "dịp cuối tuần":        "weekend short trip nearby travel quick getaway relaxation",
    "nghỉ hè":              "summer holiday beach travel outdoor water activities coastal relaxation",
    "kỳ nghỉ hè":           "summer holiday beach travel outdoor water activities coastal relaxation",
    "nghỉ đông":            "winter holiday mountain highland cozy indoor retreat travel",
    "nghỉ lễ":              "holiday travel short trip festive celebration getaway",
    "kỳ nghỉ lễ":           "holiday travel short trip festive celebration getaway",
    "cuối năm":             "year end holiday travel festive celebration cultural experience",
    "dịp cuối năm":         "year end holiday travel festive celebration cultural experience",
    "đầu năm":              "new year festival travel cultural fresh start celebration",
    "đầu năm mới":          "new year festival travel cultural fresh start celebration experience",
    "tết":                  "tet festival vietnam cultural travel tradition food celebration experience",
    "dịp tết":              "tet festival vietnam cultural travel tradition food celebration",
    "tết nguyên đán":       "lunar new year tet festival vietnam cultural celebration tradition",
    "mùa cưới":             "wedding season romantic couple travel luxury resort private scenic",
    "dịp đặc biệt":         "special occasion celebration travel luxury experience milestone",
    "ngày đặc biệt":        "special day occasion celebration travel luxury experience",
    "dịp kỷ niệm":          "anniversary special occasion celebration travel romantic scenic",
    "ngày nghỉ":            "day off holiday travel short trip nearby relaxation",
    "những ngày nghỉ":      "holidays travel short trip festive relaxation getaway",
    "tuần tới":             "upcoming trip travel planning soon getaway",
    "tháng tới":            "upcoming trip travel planning next month getaway",

    # ── English — seasons ───────────────────────────────────
    "summer":               "summer beach travel coastal swimming water activities sun outdoor",
    "this summer":          "summer beach travel coastal swimming water activities sun outdoor",
    "winter":               "winter mountain highland travel cool weather cozy indoor retreat",
    "this winter":          "winter mountain highland travel cool weather cozy indoor retreat",
    "spring":               "spring blossom outdoor travel fresh air festival nature experience",
    "this spring":          "spring blossom outdoor travel fresh air festival nature experience",
    "autumn":               "autumn leaf colorful scenic mountain highland peaceful travel",
    "fall":                 "fall leaf colorful scenic mountain highland peaceful travel",
    "monsoon":              "monsoon rainy season waterfall lush nature indoor cozy cave travel",
    "rainy season":         "rainy season waterfall lush nature green indoor cozy travel",
    "dry season":           "dry season beach outdoor clear sky activities coastal travel",

    # ── English — weather ───────────────────────────────────
    "hot":                  "hot weather cooling beach water swimming highland travel",
    "hot weather":          "hot weather cooling beach water swimming highland escape travel",
    "cold":                 "cold weather warm indoor cozy mountain scenic travel",
    "cold weather":         "cold weather warm indoor cozy mountain highland scenic retreat travel",
    "sunny":                "sunny weather beach outdoor travel picnic sightseeing clear sky",
    "foggy":                "foggy misty highland mountain atmospheric scenic travel",
    "cool":                 "cool weather highland mountain fresh air forest travel",
    "cool weather":         "cool pleasant weather highland mountain fresh air nature travel",
    "windy":                "windy coastal beach open outdoor fresh air travel",
    "mild":                 "mild weather outdoor travel walking nature relaxation",
    "mild weather":         "mild pleasant weather outdoor travel nature walking relaxation",
    "humid":                "humid weather coastal breeze beach outdoor shade travel",
    "overcast":             "overcast sky highland moody atmospheric scenic travel",
    "misty":                "misty foggy highland mountain atmospheric scenic travel photography",
    "warm":                 "warm weather beach tropical coastal outdoor travel",
    "warm weather":         "warm tropical weather beach coastal outdoor activities travel",
    "freezing":             "freezing cold mountain highland cozy indoor retreat travel",
    "stormy":               "storm weather indoor shelter cave highland travel",
    "clear":                "clear sky sunny outdoor travel scenic beach nature",
    "clear sky":            "clear sky sunny outdoor travel scenic beach nature photography",
    "dry":                  "dry weather beach outdoor travel clear sky activities",
    "wet":                  "wet rainy waterfall cave lush nature indoor travel",
    "snowy":                "snowy winter mountain highland scenic cozy travel",
    "tropical":             "tropical beach coastal warm weather water activities travel",
    "breezy":               "breezy coastal beach fresh air outdoor travel scenic",
    "balmy":                "warm mild weather beach tropical outdoor pleasant travel",
    "pleasant":             "pleasant mild weather outdoor travel nature relaxation",
    "pleasant weather":     "pleasant mild weather outdoor travel nature walking relaxation",
    "scorching":            "extreme heat cooling beach water highland travel",
    "chilly":               "chilly cold weather warm indoor mountain travel",
    "crisp":                "crisp cool weather mountain fresh air outdoor travel",
    "crisp air":            "crisp cool fresh air mountain outdoor nature travel",
    "muggy":                "muggy humid weather coastal beach shade travel",
    "grey":                 "grey overcast sky moody atmospheric highland travel",
    "hazy":                 "hazy misty weather highland atmospheric scenic travel",
    "rainy":                "rainy weather indoor waterfall cave lush travel",
    "drizzly":              "light rain indoor cafe cave relaxed travel",
    "blizzard":             "snow storm mountain highland indoor cozy travel",

    # ── English — timing ────────────────────────────────────
    "weekend":              "weekend short trip nearby travel quick getaway",
    "this weekend":         "weekend short trip nearby travel quick getaway relaxation",
    "long weekend":         "long weekend short trip getaway nearby travel relaxation",
    "off-peak":             "off peak travel quiet uncrowded peaceful affordable hidden gem",
    "off peak":             "off peak travel quiet uncrowded peaceful affordable hidden gem",
    "holiday":              "holiday travel festive getaway short trip celebration",
    "public holiday":       "public holiday travel short trip nearby festive celebration",
    "seasonal":             "seasonal travel timed festival cultural nature experience",
    "low season":           "low season travel affordable quiet uncrowded hidden gem",
    "high season":          "high season travel popular resort well serviced facilities",
    "peak season":          "peak season travel popular resort busy well serviced",
    "new year":             "new year celebration firework festive crowd travel",
}

# ═════════════════════════════════════════════════════════════
# B. SOCIAL GROUP
# ═════════════════════════════════════════════════════════════
SOCIAL_GROUP: dict[str, str] = {
    # ── Vietnamese — solo ───────────────────────────────────
    "một mình":             "solo travel independent flexible self discovery peaceful exploration",
    "đi một mình":          "solo travel independent flexible self discovery peaceful exploration",
    "du lịch một mình":     "solo travel independent flexible self discovery peaceful exploration",
    "chuyến đi một mình":   "solo travel independent flexible self paced peaceful exploration",
    "tự đi":                "solo independent travel flexible self paced exploration",
    "tự túc":               "solo independent flexible self guided travel exploration",

    # ── Vietnamese — couples ────────────────────────────────
    "cặp đôi":              "couple travel romantic private intimate scenic experience relaxation",
    "đi cặp đôi":           "couple travel romantic private intimate scenic experience",
    "du lịch cặp đôi":      "couple travel romantic private intimate scenic resort experience",
    "vợ chồng":             "couple travel romantic private resort intimate scenic relaxation",
    "đi vợ chồng":          "couple travel romantic private resort intimate scenic",
    "hai vợ chồng":         "couple travel romantic private intimate resort scenic relaxation",
    "hai người":            "couple travel romantic private intimate scenic experience",
    "đi hai người":         "couple travel romantic private intimate scenic experience",
    "người yêu":            "couple travel romantic intimate private scenic sunset experience",
    "cùng người yêu":       "couple travel romantic intimate private scenic sunset experience",
    "bạn trai":             "couple travel romantic intimate private scenic experience",
    "bạn gái":              "couple travel romantic intimate private scenic experience",
    "cùng bạn trai":        "couple travel romantic intimate private scenic sunset",
    "cùng bạn gái":         "couple travel romantic intimate private scenic sunset",
    "trăng mật":            "honeymoon luxury romantic private resort scenic experience",
    "đi trăng mật":         "honeymoon luxury romantic private resort scenic experience",
    "du lịch trăng mật":    "honeymoon luxury romantic private resort beach scenic",
    "tuần trăng mật":       "honeymoon luxury romantic private resort scenic experience",
    "mới cưới":             "honeymoon couple romantic private luxury resort scenic",
    "vừa mới cưới":         "honeymoon couple romantic private luxury resort scenic",
    "hẹn hò":               "romantic couple date intimate scenic private dinner experience",
    "đi hẹn hò":            "romantic couple date intimate scenic private experience",

    # ── Vietnamese — family ─────────────────────────────────
    "gia đình":             "family travel kid friendly safe activities education bonding experience",
    "đi gia đình":          "family travel kid friendly safe activities education bonding",
    "du lịch gia đình":     "family travel kid friendly safe comfortable activities bonding",
    "cả gia đình":          "family travel all inclusive comfortable activities bonding experience",
    "cả nhà":               "family travel all inclusive comfortable activities bonding experience",
    "đi cả nhà":            "family travel all inclusive comfortable activities bonding",
    "gia đình nhỏ":         "family travel comfortable safe activities bonding experience",
    "trẻ em":               "family travel kids safe fun activities shallow beach education",
    "có trẻ em":            "family travel kids safe fun activities shallow beach accessible",
    "có con nhỏ":           "family travel young children safe fun accessible activities",
    "con cái":              "family travel kids safe fun activities bonding education",
    "trẻ nhỏ":              "family travel young children safe fun accessible activities",
    "em bé":                "family travel baby accessible comfortable safe gentle activities",
    "có em bé":             "family travel baby safe comfortable accessible gentle",
    "ba mẹ":                "family travel parents comfortable gentle scenic cultural bonding",
    "bố mẹ":                "family travel parents comfortable gentle scenic cultural bonding",
    "cùng ba mẹ":           "family travel parents comfortable scenic cultural bonding",
    "ba mẹ và con":         "family travel parents children comfortable safe bonding experience",
    "ông bà":               "senior travel accessible comfortable gentle heritage cultural experience",
    "ông bà cháu":          "multigenerational family travel accessible comfortable gentle scenic",
    "nhiều thế hệ":         "multigenerational family travel accessible comfortable bonding cultural",
    "ba thế hệ":            "multigenerational family travel accessible comfortable bonding",
    "người thân":           "family travel comfortable gentle scenic cultural bonding",
    "cùng người thân":      "family travel comfortable gentle scenic cultural bonding experience",

    # ── Vietnamese — friends ────────────────────────────────
    "bạn bè":               "group travel friends social fun nightlife activities adventure",
    "đi với bạn bè":        "group travel friends social fun activities adventure",
    "cùng bạn bè":          "group travel friends social fun activities adventure",
    "nhóm bạn":             "group travel social activities adventure fun exploration",
    "đi nhóm":              "group travel social activities adventure fun variety",
    "đi nhóm bạn":          "group travel friends social activities adventure fun",
    "bạn thân":             "friends travel close bonding relaxed fun flexible experience",
    "đi với bạn thân":      "close friends travel bonding fun relaxed flexible experience",
    "hội bạn":              "group travel friends social lively adventure fun exploration",
    "cả nhóm":              "group travel social activities flexible organized experience",
    "anh em":               "siblings travel social fun adventure bonding flexible",
    "chị em":               "friends travel social wellness fun relaxed flexible experience",
    "nhóm nhỏ":             "small group travel flexible intimate activities adventure",
    "nhóm lớn":             "large group travel organized resort activities social experience",

    # ── Vietnamese — work/specific groups ───────────────────
    "đồng nghiệp":          "team travel group team building activities social bonding",
    "cùng đồng nghiệp":     "team travel group team building activities social bonding",
    "công ty":              "company travel team building organized group activities social",
    "du lịch công ty":      "company travel team building organized group activities social",
    "sinh viên":            "student travel budget backpacker social hostel affordable fun",
    "học sinh":             "student travel budget social affordable fun educational",
    "người già":            "senior travel accessible gentle comfortable scenic cultural experience",
    "cao tuổi":             "senior travel accessible gentle comfortable scenic cultural",
    "người cao tuổi":       "senior elderly travel accessible gentle comfortable scenic cultural",
    "hưu trí":              "retiree travel comfortable accessible gentle cultural scenic experience",
    "thanh niên":           "young adult travel active social fun budget adventure",
    "hưu":                  "retiree travel comfortable accessible gentle cultural experience",

    # ── English — solo ──────────────────────────────────────
    "solo":                 "solo travel independent flexible self discovery peaceful exploration",
    "alone":                "solo travel independent flexible self paced peaceful experience",
    "by myself":            "solo travel independent flexible self paced peaceful",
    "travelling alone":     "solo travel independent flexible self discovery peaceful",
    "traveling alone":      "solo travel independent flexible self discovery peaceful",
    "on my own":            "solo travel independent flexible self paced peaceful exploration",

    # ── English — couples ───────────────────────────────────
    "couple":               "couple travel romantic intimate private scenic experience",
    "couples":              "couple travel romantic intimate private scenic resort experience",
    "with my partner":      "couple travel romantic intimate private scenic experience",
    "with my wife":         "couple travel romantic intimate private scenic resort",
    "with my husband":      "couple travel romantic intimate private scenic resort",
    "with my girlfriend":   "couple travel romantic intimate private scenic experience",
    "with my boyfriend":    "couple travel romantic intimate private scenic experience",
    "newlyweds":            "honeymoon couple romantic luxury private resort scenic",
    "honeymoon":            "honeymoon luxury romantic private resort scenic experience",
    "anniversary trip":     "anniversary romantic couple special scenic luxury experience",
    "romantic trip":        "romantic couple intimate private scenic luxury experience",
    "date":                 "romantic couple date intimate scenic private dinner",

    # ── English — family ────────────────────────────────────
    "family":               "family travel kid friendly safe comfortable activities bonding",
    "with kids":            "family travel kids safe fun activities shallow beach accessible",
    "with children":        "family travel children safe fun activities accessible educational",
    "with my kids":         "family travel kids safe fun activities shallow beach",
    "with baby":            "family travel baby safe accessible comfortable gentle",
    "with toddler":         "family travel toddler safe accessible gentle activities",
    "with parents":         "family travel parents comfortable scenic cultural bonding",
    "with grandparents":    "multigenerational family travel accessible comfortable gentle",
    "multigenerational":    "multigenerational family travel accessible comfortable bonding",
    "multi generational":   "multigenerational family travel accessible comfortable bonding",

    # ── English — friends ───────────────────────────────────
    "friends":              "group travel social fun nightlife activities adventure",
    "with friends":         "group travel friends social fun activities adventure",
    "group":                "group travel social activities flexible variety experience",
    "group trip":           "group travel social activities organized fun variety",
    "squad":                "group travel friends social fun adventure activities",
    "crew":                 "group travel social activities adventure fun",
    "lads":                 "group travel friends social fun adventure activities",
    "girls trip":           "group travel friends social wellness fun relaxed",
    "guys trip":            "group travel friends social fun adventure active",
    "bachelorette":         "group travel friends social fun celebration party",
    "bachelor":             "group travel friends social fun adventure celebration",

    # ── English — work/specific ─────────────────────────────
    "colleagues":           "team travel group team building social activities",
    "coworkers":            "team travel organized group activities social bonding",
    "corporate":            "corporate team travel organized conference group activities",
    "students":             "student travel budget backpacker social hostel affordable",
    "backpackers":          "backpacker budget hostel social flexible exploration",
    "elderly":              "senior travel accessible gentle comfortable scenic cultural",
    "seniors":              "senior travel accessible gentle comfortable scenic cultural",
    "retirees":             "retiree travel comfortable accessible gentle cultural scenic",
}

# ═════════════════════════════════════════════════════════════
# C. TRIP DURATION
# ═════════════════════════════════════════════════════════════
TRIP_DURATION: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "một ngày":             "day trip short travel",
    "đi một ngày":          "day trip short travel",
    "chuyến một ngày":      "day trip short travel",
    "hai ngày":             "short trip travel two days",
    "đi hai ngày":          "short trip travel two days",
    "hai ngày một đêm":     "short trip travel overnight two days",
    "2 ngày 1 đêm":         "short trip travel overnight two days",
    "ba ngày":              "short trip travel three days",
    "đi ba ngày":           "short trip travel three days",
    "ba ngày hai đêm":      "short trip travel three days two nights",
    "3 ngày 2 đêm":         "short trip travel three days two nights",
    "bốn ngày":             "short trip travel",
    "năm ngày":             "short trip travel",
    "sáu ngày":             "extended trip travel",
    "một tuần":             "week long travel extended trip",
    "đi một tuần":          "week long travel extended trip",
    "cả tuần":              "week long travel extended trip",
    "hai tuần":             "long travel extended trip",
    "đi hai tuần":          "long travel extended trip",
    "dài ngày":             "long travel extended trip",
    "chuyến dài":           "long extended travel trip",
    "chuyến dài ngày":      "long extended travel multi day trip",
    "ngắn ngày":            "short trip travel quick",
    "chuyến ngắn":          "short trip travel quick getaway",
    "vài ngày":             "short trip travel few days",
    "cả tháng":             "long travel extended month trip",
    "một buổi":             "half day trip short travel",
    "nửa ngày":             "half day trip short travel",
    "vài giờ":              "short trip nearby travel quick",
    "qua đêm":              "overnight trip short travel",
    "đêm":                  "overnight short trip travel",
    "cuối tuần":            "weekend short trip travel",

    # ── English ─────────────────────────────────────────────
    "day trip":             "day trip short nearby travel",
    "one day":              "day trip short travel",
    "1 day":                "day trip short travel",
    "overnight":            "overnight short trip travel",
    "two days":             "short trip travel two days",
    "2 days":               "short trip travel two days",
    "three days":           "short trip travel three days",
    "3 days":               "short trip travel three days",
    "4 days":               "short trip travel",
    "five days":            "short trip travel",
    "5 days":               "short trip travel",
    "one week":             "week long travel extended trip",
    "1 week":               "week long travel extended trip",
    "a week":               "week long travel extended trip",
    "two weeks":            "long travel extended trip",
    "2 weeks":              "long travel extended trip",
    "a month":              "long travel extended trip",
    "all summer":           "long travel extended summer trip",
    "gap year":             "long travel extended exploration",
    "weekend trip":         "weekend short trip travel quick",
    "long weekend":         "long weekend short trip travel",
    "short trip":           "short trip travel quick getaway",
    "long trip":            "long extended travel trip",
    "quick trip":           "short quick trip travel nearby",
    "extended trip":        "long extended travel trip",
    "half day":             "half day short trip travel",
    "half-day":             "half day short trip travel",
    "fortnight":            "long travel two weeks extended",
    "few days":             "short trip travel few days",
    "several days":         "short trip travel few days",
    "a few days":           "short trip travel few days",
    "couple of days":       "short trip travel two days",
    "week-long":            "week long travel extended trip",
}

# ═════════════════════════════════════════════════════════════
# D. TRIP DISTANCE
# ═════════════════════════════════════════════════════════════
TRIP_DISTANCE: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "gần":                  "nearby travel short distance local accessible",
    "gần nhà":              "nearby travel short distance home local accessible",
    "gần đây":              "nearby local travel short distance accessible",
    "gần thành phố":        "nearby urban city travel short distance accessible",
    "gần Hà Nội":           "nearby Hanoi travel short distance north vietnam accessible",
    "gần Sài Gòn":          "nearby Saigon Ho Chi Minh travel short distance south vietnam",
    "gần thôi":             "nearby short distance local travel accessible",
    "không xa":             "nearby not far local travel accessible short distance",
    "không xa lắm":         "nearby local travel accessible short distance",
    "cách không xa":        "nearby not far local travel accessible",
    "trong nước":           "domestic vietnam travel local",
    "du lịch trong nước":   "domestic vietnam travel local exploration",
    "quốc tế":              "international travel abroad overseas",
    "du lịch quốc tế":      "international abroad overseas travel",
    "nước ngoài":           "international travel abroad overseas foreign",
    "đi nước ngoài":        "international travel abroad overseas",
    "ra nước ngoài":        "international travel abroad overseas foreign",
    "xa":                   "far travel distant long journey",
    "xa xôi":               "remote distant far travel long journey",
    "trong vùng":           "nearby regional travel local accessible",
    "khắp nơi":             "anywhere travel flexible open destination",
    "trong tỉnh":           "nearby local province travel short distance",
    "trong thành phố":      "urban city local travel nearby accessible",
    "ngoại thành":          "suburban outskirts nearby travel accessible",
    "ngoại ô":              "suburban outskirts nearby travel accessible",

    # ── English ─────────────────────────────────────────────
    "nearby":               "nearby travel short distance local accessible",
    "near":                 "nearby travel short distance local accessible",
    "close to home":        "nearby home local travel short distance accessible",
    "close by":             "nearby local travel accessible short distance",
    "not far":              "nearby local travel short distance accessible",
    "local":                "local nearby travel accessible community",
    "domestic":             "domestic local country travel",
    "in country":           "domestic local country travel",
    "international":        "international abroad overseas travel",
    "overseas":             "international abroad overseas travel",
    "abroad":               "international abroad overseas foreign travel",
    "foreign":              "international abroad foreign overseas travel",
    "far":                  "far distant travel long journey",
    "far away":             "far distant travel remote long journey",
    "regional":             "nearby regional travel local accessible",
    "cross-country":        "domestic cross country travel long distance",
    "cross country":        "domestic cross country travel long distance",
    "worldwide":            "international worldwide travel overseas",
    "local area":           "nearby local area travel accessible",
    "within driving":       "nearby driving distance local travel accessible",
    "road distance":        "nearby driving distance local travel",
    "flying distance":      "far travel air flight destination",
    "flight away":          "far travel air flight destination",
}

# ═════════════════════════════════════════════════════════════
# E. BUDGET LEVEL
# ═════════════════════════════════════════════════════════════
BUDGET_LEVEL: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "tiết kiệm":            "budget travel cheap affordable hostel backpacker",
    "du lịch tiết kiệm":    "budget travel cheap affordable hostel backpacker",
    "chuyến tiết kiệm":     "budget travel cheap affordable hostel backpacker",
    "bình dân":             "mid range travel affordable comfortable",
    "tầm bình dân":         "mid range travel affordable comfortable value",
    "trung bình":           "mid range travel balanced comfortable",
    "chi phí trung bình":   "mid range travel balanced comfortable value",
    "sang trọng":           "luxury travel premium resort exclusive",
    "du lịch sang trọng":   "luxury travel premium resort exclusive upscale",
    "vừa túi":              "budget travel affordable comfortable",
    "vừa ví":               "budget travel affordable comfortable",
    "vừa tiền":             "budget travel affordable comfortable value",
    "vừa tầm":              "mid range budget travel affordable comfortable",
    "cao cấp":              "luxury travel premium exclusive resort",
    "dịch vụ cao cấp":      "luxury premium service travel exclusive resort",
    "tằn tiện":             "budget travel cheap minimal backpacker",
    "phóng khoáng":         "luxury travel premium high end",
    "không giới hạn":       "luxury travel unlimited premium",
    "giá rẻ":               "budget travel cheap affordable",
    "rẻ":                   "budget travel cheap affordable",
    "rẻ thôi":              "budget travel cheap affordable minimal",
    "không tốn nhiều":      "budget travel affordable cheap value",
    "hạng sang":            "luxury travel premium exclusive",
    "5 sao":                "luxury 5 star resort premium exclusive travel",
    "khách sạn 5 sao":      "luxury 5 star hotel resort premium exclusive travel",
    "resort cao cấp":       "luxury resort premium exclusive beach travel",
    "tiêu xài":             "luxury travel splurge premium",
    "siêu tiết kiệm":       "very budget travel ultra cheap minimal backpacker",
    "cực rẻ":               "very budget travel ultra cheap minimal",
    "không cần lo tiền":    "luxury travel no budget limit premium exclusive",

    # ── English ─────────────────────────────────────────────
    "budget":               "budget travel cheap affordable hostel",
    "budget travel":        "budget travel cheap affordable hostel backpacker",
    "on a budget":          "budget travel cheap affordable hostel backpacker",
    "affordable":           "mid range travel affordable comfortable",
    "cheap":                "budget travel cheap minimal affordable",
    "cheap trip":           "budget travel cheap affordable minimal",
    "moderate":             "mid range travel balanced comfortable",
    "mid range":            "mid range travel balanced comfortable",
    "mid-range":            "mid range travel balanced comfortable",
    "upscale":              "premium travel quality comfortable upscale",
    "luxury":               "luxury travel premium exclusive resort",
    "luxury travel":        "luxury travel premium exclusive resort fine dining",
    "splurge":              "luxury travel premium high end splurge",
    "treat myself":         "luxury travel premium splurge high end",
    "premium":              "premium travel luxury quality exclusive",
    "cheap and cheerful":   "budget fun affordable travel comfortable",
    "free":                 "budget travel low cost free activities",
    "expensive":            "luxury travel premium exclusive",
    "frugal":               "budget travel minimal cheap value",
    "lavish":               "luxury travel premium resort lavish",
    "economical":           "budget travel affordable value economical",
    "wallet friendly":      "budget travel affordable value comfortable",
    "wallet-friendly":      "budget travel affordable value comfortable",
    "cost effective":       "budget travel affordable value",
    "cost-effective":       "budget travel affordable value",
    "high end":             "luxury travel high end premium exclusive",
    "high-end":             "luxury travel high end premium exclusive",
    "5 star":               "luxury 5 star resort premium exclusive travel",
    "five star":            "luxury 5 star resort premium exclusive travel",
    "inexpensive":          "budget travel affordable value",
    "value for money":      "mid range travel value comfortable affordable",
    "thrifty":              "budget travel minimal cheap thrifty",
    "extravagant":          "luxury travel premium extravagant exclusive",
    "reasonable":           "mid range travel affordable reasonable",
    "blowout":              "luxury travel splurge premium blowout",
    "no expense spared":    "luxury travel unlimited premium exclusive",
}

# ═════════════════════════════════════════════════════════════
# F. PACE & STYLE
# ═════════════════════════════════════════════════════════════
PACE: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "chậm rãi":             "slow travel relaxed peaceful gentle experience scenic exploration",
    "đi chậm rãi":          "slow travel relaxed peaceful gentle scenic exploration",
    "thư thả":              "leisure travel slow relaxed comfortable experience scenic",
    "đi thư thả":           "leisure slow travel relaxed comfortable scenic experience",
    "thoải mái":            "relaxed travel flexible comfortable no rush experience",
    "đi thoải mái":         "relaxed travel flexible comfortable no rush scenic",
    "năng động":            "active travel energetic activities adventure exploration",
    "tự do":                "flexible travel spontaneous independent exploration free roam",
    "đi tự do":             "flexible independent travel spontaneous exploration free",
    "kế hoạch":             "planned travel structured itinerary organized experience",
    "có kế hoạch":          "planned structured travel organized itinerary",
    "linh hoạt":            "flexible travel adaptable spontaneous semi structured",
    "tự túc":               "independent travel self guided flexible exploration",
    "chill":                "relaxed travel slow peaceful no rush experience",
    "chill thôi":           "very relaxed slow travel chill peaceful no rush",
    "vội vã":               "fast paced travel packed activities efficient exploration",
    "không vội":            "slow travel relaxed no rush peaceful experience",
    "không vội vàng":       "slow travel relaxed no rush peaceful experience",
    "từ từ":                "slow leisurely travel relaxed no rush peaceful",
    "tự lái":               "self drive travel road trip flexible independent scenic",
    "lái xe":               "self drive travel road trip scenic flexible",
    "tự lái xe":            "self drive travel road trip flexible independent scenic",
    "theo tour":            "guided tour travel organized structured itinerary",
    "đi tour":              "guided tour travel organized structured itinerary",
    "book tour":            "guided tour travel organized structured itinerary",
    "phượt":                "backpacker travel flexible independent road trip adventure",
    "đi phượt":             "backpacker travel flexible independent road trip adventure",
    "hướng dẫn":            "guided travel organized tour cultural sightseeing",
    "có hướng dẫn viên":    "guided travel tour cultural organized sightseeing",

    # ── English ─────────────────────────────────────────────
    "leisurely":            "slow travel relaxed scenic gentle experience",
    "relaxed":              "relaxed travel slow comfortable scenic experience",
    "packed":               "packed busy travel activities efficient exploration",
    "packed itinerary":     "packed busy travel activities efficient organized exploration",
    "spontaneous":          "spontaneous travel flexible exploration adventure",
    "structured":           "structured travel planned organized itinerary",
    "guided":               "guided travel organized tour itinerary",
    "guided tour":          "guided tour travel organized structured sightseeing",
    "flexible":             "flexible travel adaptable spontaneous",
    "independent":          "independent travel self guided exploration",
    "organized":            "organized travel planned itinerary",
    "unplanned":            "spontaneous travel flexible open exploration",
    "self drive":           "self drive travel road trip flexible exploration",
    "self-drive":           "self drive travel road trip flexible exploration",
    "backpacking":          "backpacker travel budget flexible exploration",
    "fly in":               "resort travel organized comfortable guided",
    "fly-in":               "resort travel organized comfortable guided",
    "road trip":            "road trip travel scenic drive flexible exploration",
    "packaged":             "package tour travel organized all inclusive",
    "package tour":         "package tour travel organized all inclusive",
    "all inclusive":        "all inclusive resort travel organized comfortable",
    "all-inclusive":        "all inclusive resort travel organized comfortable",
    "unhurried":            "slow travel peaceful gentle exploration",
    "easygoing":            "relaxed travel flexible comfortable",
    "easy going":           "relaxed travel flexible comfortable",
    "whirlwind":            "fast travel packed activities efficient",
    "whirlwind tour":       "fast packed activities efficient travel sightseeing",
    "impromptu":            "spontaneous travel flexible exploration",
    "regimented":           "structured travel planned organized",
    "escorted":             "guided escorted travel organized tour",
    "free form":            "flexible travel spontaneous exploration",
    "self planned":         "independent travel flexible self guided",
    "self-planned":         "independent travel flexible self guided",
    "methodical":           "organized travel planned structured",
    "freewheeling":         "flexible travel spontaneous adventure",
    "slow travel":          "slow travel immersive relaxed peaceful experience",
    "fast travel":          "fast paced travel packed activities efficient",
    "adventure travel":     "adventure travel outdoor active exploration",
    "luxury travel":        "luxury travel premium resort exclusive comfortable",
    "eco travel":           "eco tourism sustainable nature conservation responsible travel",
    "volunteer":            "volunteer travel community social impact meaningful",
    "workation":            "workation remote work travel wifi relaxed balance",
    "digital nomad":        "digital nomad remote work travel wifi flexible",
}

# ═════════════════════════════════════════════════════════════
# G. NATURE & LANDSCAPE
# ═════════════════════════════════════════════════════════════
NATURE_LANDSCAPE: dict[str, str] = {
    # ── Vietnamese — general nature ─────────────────────────
    "thiên nhiên":          "nature outdoor greenery scenic landscape fresh air peaceful",
    "đến với thiên nhiên":  "nature outdoor greenery scenic landscape fresh air peaceful",
    "gần thiên nhiên":      "nature nearby outdoor greenery scenic landscape fresh air peaceful",
    "vào thiên nhiên":      "nature outdoor greenery scenic landscape fresh air peaceful",
    "hòa mình vào thiên nhiên": "nature immersive outdoor greenery scenic peaceful",
    "cảnh thiên nhiên":     "natural scenery landscape scenic outdoor photography",
    "cảnh đẹp thiên nhiên": "beautiful natural scenery landscape scenic outdoor photography",

    # ── Vietnamese — terrain ────────────────────────────────
    "núi":                  "mountain highland altitude peak summit trail trekking scenic",
    "lên núi":              "mountain highland trekking summit trail scenic",
    "đi núi":               "mountain highland trekking trail scenic nature",
    "vùng núi":             "mountain highland region scenic trekking nature",
    "núi cao":              "high mountain highland altitude summit trail trekking",
    "đồi":                  "hill rolling meadow green scenic walk gentle nature",
    "đồi núi":              "hill mountain highland scenic walk nature trekking",
    "cao nguyên":           "plateau highland grassland scenic wide open altitude",
    "vùng cao":             "highland high altitude mountain scenic trekking nature",
    "miền núi":             "mountain highland region scenic trekking nature culture",
    "thung lũng":           "valley gorge panoramic highland scenic hiking nature",
    "hang động":            "cave exploration geological adventure underground scenic",
    "vào hang":             "cave exploration underground adventure scenic",
    "sa mạc":               "desert dunes arid vast unique landscape",
    "đồng lúa":             "rice field paddy rural pastoral landscape green scenic",
    "ruộng bậc thang":      "terraced rice field highland ethnic scenic photography",
    "cánh đồng":            "field plains open countryside rural scenic nature",
    "vách đá":              "cliff coastal dramatic viewpoint scenic photography",

    # ── Vietnamese — water ──────────────────────────────────
    "biển":                 "beach coastal sea ocean wave sand surf outdoor",
    "ra biển":              "beach coastal sea travel outdoor swimming",
    "đi biển":              "beach coastal sea travel outdoor swimming sun",
    "bãi biển":             "beach coastal sand sea outdoor swimming sun",
    "vùng biển":            "coastal beach sea region outdoor swimming travel",
    "biển xanh":            "blue sea beach coastal clear water swimming snorkeling",
    "nước biển":            "sea ocean swimming coastal beach outdoor",
    "sóng biển":            "beach waves surf coastal outdoor swimming",
    "đảo":                  "island tropical isolated beach snorkeling reef scenic",
    "ra đảo":               "island tropical beach snorkeling reef travel",
    "đi đảo":               "island tropical beach snorkeling reef travel",
    "vịnh":                 "bay cove sheltered beach snorkeling scenic",
    "hồ":                   "lake calm serene boating reflection scenic nature",
    "bên hồ":               "lakeside calm serene scenic nature relaxation",
    "sông":                 "river boat cruise kayak scenic waterway nature",
    "bên sông":             "riverside scenic nature relaxation boat cruise",
    "suối":                 "stream creek freshwater cool nature scenic",
    "thác nước":            "waterfall cascade scenic nature photography hiking",
    "đến thác":             "waterfall cascade scenic nature photography hiking",
    "rừng ngập mặn":        "mangrove eco tourism kayak birdwatching nature",
    "san hô":               "coral reef diving snorkeling marine tropical",
    "mạch nước nóng":       "hot spring thermal mineral water wellness relaxation",
    "suối khoáng":          "mineral spring thermal wellness relaxation healing",
    "suối nước nóng":       "hot spring thermal mineral wellness relaxation healing",

    # ── Vietnamese — vegetation ─────────────────────────────
    "rừng":                 "forest jungle eco tourism canopy wildlife trees nature",
    "vào rừng":             "forest jungle eco nature trekking wildlife",
    "đi rừng":              "forest jungle eco nature trekking wildlife adventure",
    "rừng nhiệt đới":       "rainforest tropical dense canopy wildlife eco nature",
    "vườn quốc gia":        "national park wildlife conservation trekking eco nature",
    "khu bảo tồn":          "nature reserve conservation wildlife sanctuary eco",
    "rừng thông":           "pine forest highland cool aromatic scenic walk",
    "đồng cỏ":              "grassland meadow open air scenic mild nature",
    "vườn hoa":             "flower garden bloom colorful scenic photography",
    "hoa":                  "flowers bloom colorful scenic photography nature",
    "vườn trà":             "tea plantation highland green rows scenic cultural",
    "đồi chè":              "tea hill plantation highland green scenic photography",
    "vườn cà phê":          "coffee plantation highland culture local experience",

    # ── Vietnamese — sky ────────────────────────────────────
    "ngắm sao":             "stargazing dark sky astronomy rural night clear peaceful",
    "bầu trời sao":         "stargazing dark sky astronomy night clear scenic",
    "bình minh":            "sunrise early morning golden scenic photography",
    "ngắm bình minh":       "sunrise early morning golden scenic photography peaceful",
    "hoàng hôn":            "sunset golden hour scenic romantic photography",
    "ngắm hoàng hôn":       "sunset golden hour scenic romantic photography couple",
    "sương mù":             "misty foggy atmospheric ethereal highland scenic photography",
    "mây":                  "cloud highland misty ethereal scenic dramatic photography",

    # ── English — general ───────────────────────────────────
    "nature":               "nature outdoor scenic greenery landscape fresh air",
    "in nature":            "nature outdoor scenic greenery landscape fresh air peaceful",
    "natural":              "natural outdoor scenic greenery landscape nature",
    "great outdoors":       "outdoor nature scenic adventure activities fresh air",
    "wilderness":           "wilderness outdoor nature remote adventure trekking",
    "scenery":              "scenery scenic landscape beautiful photography nature",
    "scenic":               "scenic beautiful landscape photography outdoor nature",
    "landscape":            "landscape scenic photography outdoor nature",

    # ── English — terrain ───────────────────────────────────
    "beach":                "beach coastal ocean wave sand sun surf outdoor",
    "the beach":            "beach coastal ocean wave sand sun surf outdoor",
    "at the beach":         "beach coastal ocean wave sand sun swimming outdoor",
    "beach trip":           "beach coastal travel swimming sun sand outdoor",
    "mountain":             "mountain highland trek summit trail peak altitude",
    "mountains":            "mountains highland trek summit trail scenic altitude",
    "the mountains":        "mountains highland trek summit trail scenic altitude",
    "hiking":               "hiking trail mountain nature outdoor scenic trekking",
    "trekking":             "trekking hiking mountain trail outdoor nature",
    "forest":               "forest jungle eco canopy wildlife trees nature",
    "the forest":           "forest jungle eco canopy wildlife trees nature",
    "waterfall":            "waterfall cascade scenic nature photography hiking",
    "waterfalls":           "waterfalls cascades scenic nature photography hiking",
    "lake":                 "lake serene calm boating rowing reflection nature",
    "lakeside":             "lakeside calm serene scenic nature relaxation",
    "cave":                 "cave underground exploration geological adventure",
    "caves":                "caves underground exploration geological adventure",
    "island":               "island tropical isolated beach snorkeling reef",
    "islands":              "islands tropical isolated beach snorkeling reef",
    "river":                "river boat cruise kayak scenic waterway nature",
    "riverside":            "riverside scenic nature relaxation boat cruise",
    "sea":                  "sea ocean coastal beach surf horizon outdoor",
    "ocean":                "ocean sea coastal beach surf horizon outdoor",
    "coast":                "coastal beach ocean shoreline scenic breeze",
    "coastal":              "coastal beach ocean shoreline scenic breeze",
    "desert":               "desert dunes arid vast unique landscape",
    "jungle":               "jungle rainforest eco tourism wildlife trekking dense",
    "valley":               "valley scenic gorge panoramic highland hiking nature",
    "cliff":                "cliff coastal dramatic viewpoint scenic photography",
    "hot spring":           "hot spring thermal bath wellness relaxation mineral",
    "hot springs":          "hot springs thermal bath wellness relaxation mineral",
    "rice field":           "rice field paddy rural pastoral green landscape",
    "rice fields":          "rice fields paddy rural pastoral green landscape scenic",
    "rice terraces":        "terraced rice field highland scenic photography",
    "national park":        "national park wildlife conservation trekking hiking",
    "nature reserve":       "nature reserve conservation wildlife eco sanctuary",
    "coral reef":           "coral reef diving snorkeling marine tropical",
    "mangrove":             "mangrove eco kayak birdwatching nature waterway",
    "lagoon":               "lagoon calm sheltered turquoise scenic photography",
    "bay":                  "bay cove sheltered beach snorkeling scenic",
    "tea plantation":       "tea plantation highland rows green scenic cultural",
    "flower field":         "flower field bloom colorful scenic photography",
    "sunset":               "sunset golden romantic scenic photography outdoor",
    "sunrise":              "sunrise early golden scenic photography peaceful",
    "stargazing":           "stargazing dark sky astronomy rural night peaceful",
    "star gazing":          "stargazing dark sky astronomy rural night peaceful",
}

# ═════════════════════════════════════════════════════════════
# H. TRAVEL INTENT
# ═════════════════════════════════════════════════════════════
TRAVEL_INTENT: dict[str, str] = {
    # ── Vietnamese — wanting to go ──────────────────────────
    "muốn đi":              "travel wanting to go trip exploration experience",
    "muốn du lịch":         "travel wanting to travel trip exploration experience",
    "muốn đi chơi":         "travel leisure trip fun exploration experience",
    "muốn đi du lịch":      "travel wanting trip exploration experience",
    "muốn đi xa":           "travel far trip exploration distant experience",
    "muốn đi thăm":         "travel visit trip sightseeing experience",
    "muốn đến":             "travel wanting to visit destination experience",
    "muốn thăm":            "travel visit sightseeing cultural experience",
    "muốn trải nghiệm":     "travel wanting new experience cultural authentic",
    "muốn khám phá":        "travel wanting exploration discovery adventure",
    "muốn tham quan":       "travel sightseeing tour visit cultural experience",
    "muốn ghé":             "travel stop visit destination experience",
    "muốn thấy":            "travel seeing visit sightseeing experience",
    "muốn tận hưởng":       "travel enjoy relaxation experience leisure",
    "đang tìm":             "searching looking for travel destination experience",
    "tìm kiếm":             "searching looking for travel destination experience",
    "đang nghĩ đến":        "planning considering travel destination",
    "đang lên kế hoạch":    "planning travel trip organizing itinerary",
    "đang chuẩn bị":        "preparing planning travel trip",
    "sẽ đi":                "upcoming planned travel trip",
    "định đi":              "planning intending travel trip",
    "dự định đi":           "planning intending travel trip",

    # ── Vietnamese — exploring ──────────────────────────────
    "khám phá":             "exploration discovery adventure outdoor cultural new experience",
    "đi khám phá":          "exploration discovery adventure cultural new travel experience",
    "khám phá vùng đất mới":"new destination discovery exploration travel adventure",
    "trải nghiệm":          "new experience cultural authentic local immersive travel",
    "trải nghiệm mới":      "new experience cultural authentic local immersive travel",
    "tham quan":            "sightseeing tour guided heritage cultural visit",
    "đi tham quan":         "sightseeing tour guided heritage cultural visit travel",
    "thăm quan":            "sightseeing tour guided heritage cultural visit",
    "thăm":                 "visit sightseeing cultural experience travel",
    "ghé thăm":             "visit stop sightseeing cultural experience",
    "đặt chân đến":         "visit destination travel arrival experience",
    "chuyến đi":            "travel trip journey exploration experience",
    "chuyến du lịch":       "travel tourism trip exploration experience",
    "chuyến đi chơi":       "leisure trip travel fun exploration",
    "chuyến nghỉ dưỡng":    "resort relaxation trip travel rest wellness",
    "chuyến phiêu lưu":     "adventure trip travel exploration outdoor",
    "hành trình":           "journey trip travel route exploration experience",
    "du ngoạn":             "scenic tour guided drive nature landscape",
    "du lịch":              "travel tourism trip exploration experience",
    "đi chơi":              "leisure travel fun outing trip",
    "đi dạo":               "walking stroll leisurely travel gentle exploration",
    "đi thăm":              "visit sightseeing travel cultural heritage experience",

    # ── English ─────────────────────────────────────────────
    "want to go":           "travel wanting trip exploration experience",
    "want to travel":       "travel wanting trip exploration experience",
    "want to visit":        "travel visit destination sightseeing experience",
    "want to explore":      "exploration discovery adventure travel cultural",
    "want to see":          "sightseeing visit travel destination experience",
    "want to experience":   "new experience cultural authentic immersive travel",
    "looking for":          "searching travel destination experience",
    "planning a trip":      "planning travel trip organizing itinerary",
    "planning to go":       "planning travel trip upcoming",
    "thinking of going":    "considering planning travel trip destination",
    "considering":          "considering planning travel trip destination",
    "trip":                 "travel trip journey exploration experience",
    "travel":               "travel trip journey tourism exploration",
    "vacation":             "vacation travel holiday leisure relaxation experience",
    "holiday":              "holiday travel leisure vacation relaxation",
    "getaway":              "getaway travel short trip leisure relaxation",
    "escape":               "escape travel getaway relaxation leisure",
    "explore":              "exploration discovery travel adventure cultural",
    "discover":             "discovery exploration travel adventure new experience",
    "adventure":            "adventure travel exploration outdoor active discovery",
    "journey":              "journey travel trip exploration experience",
    "excursion":            "excursion trip sightseeing travel day experience",
    "sightseeing":          "sightseeing tour travel guided heritage cultural",
    "visit":                "visit sightseeing cultural travel heritage",
}

# ═════════════════════════════════════════════════════════════
# I. MOOD & ATMOSPHERE
# ═════════════════════════════════════════════════════════════
MOOD_ATMOSPHERE: dict[str, str] = {
    # ── Vietnamese — tranquil ───────────────────────────────
    "yên tĩnh":             "quiet peaceful tranquil secluded serene slow travel relaxed nature",
    "yên bình":             "quiet peaceful calm serene nature gentle slow travel",
    "thanh bình":           "peaceful calm serene quiet nature gentle travel",
    "bình yên":             "peaceful calm serene nature gentle slow travel retreat",
    "thanh thản":           "tranquil serene mindful calm restorative slow travel wellness",
    "tĩnh lặng":            "quiet silent peaceful tranquil secluded nature retreat",
    "yên ắng":              "quiet peaceful tranquil serene secluded nature",
    "vắng vẻ":              "quiet uncrowded secluded peaceful off beaten path",
    "nhẹ nhàng":            "gentle soft slow relaxed peaceful travel nature",
    "ẩn mình":              "hidden gem off beaten path undiscovered quiet secluded",
    "riêng tư":             "private secluded exclusive quiet intimate travel",
    "tách biệt":            "secluded isolated private quiet nature retreat",
    "hoang vắng":           "remote wild deserted quiet nature secluded adventure",
    "hẻo lánh":             "remote secluded off beaten path nature quiet travel",
    "cô tịch":              "solitude quiet peaceful secluded nature retreat",

    # ── Vietnamese — lively ─────────────────────────────────
    "sôi động":             "vibrant lively energetic social crowd entertainment nightlife",
    "nhộn nhịp":            "bustling lively crowded vibrant social market city",
    "náo nhiệt":            "festive lively loud energetic social party crowd",
    "vui vẻ":               "fun lively cheerful social activities entertainment",
    "tấp nập":              "busy bustling lively crowded vibrant city market",
    "phồn hoa":             "vibrant urban lively cosmopolitan city entertainment",

    # ── Vietnamese — romantic ───────────────────────────────
    "lãng mạn":             "romantic sunset couple private intimate scenic beautiful",
    "thơ mộng":             "dreamy picturesque scenic poetic gentle beautiful romantic",
    "huyền ảo":             "magical ethereal dreamy beautiful scenic atmospheric",
    "mơ mộng":              "dreamy romantic scenic poetic beautiful gentle",

    # ── Vietnamese — dramatic/wild ──────────────────────────
    "hùng vĩ":              "grand majestic dramatic vast imposing scenic nature",
    "hùng tráng":           "grand majestic dramatic powerful scenic nature",
    "hoang dã":             "wild untamed remote raw nature rugged adventure",
    "nguyên sinh":          "pristine untouched primary forest pure remote nature",
    "huyền bí":             "mysterious atmospheric misty fog ethereal dramatic",
    "kỳ bí":                "mysterious ethereal atmospheric scenic dramatic nature",

    # ── Vietnamese — cozy/warm ─────────────────────────────
    "ấm cúng":              "cozy warm intimate comfortable indoor fireside",
    "ấm áp":                "warm cozy comfortable intimate travel",
    "thân mật":             "intimate private cozy warm personal",

    # ── Vietnamese — modern/rustic ──────────────────────────
    "hiện đại":             "modern contemporary urban design sleek city",
    "cổ kính":              "vintage antique old world nostalgic charm historic",
    "mộc mạc":              "rustic traditional wooden countryside charm authentic",
    "hoài cổ":              "retro nostalgic vintage old world sentimental charm",
    "cổ điển":              "classic heritage traditional atmospheric vintage",

    # ── Vietnamese — aesthetic ──────────────────────────────
    "đẹp như tranh":        "picturesque scenic beautiful photography stunning",
    "đẹp":                  "beautiful scenic photography stunning nature travel",
    "đẹp lắm":              "very beautiful scenic stunning photography travel",
    "rất đẹp":              "very beautiful scenic stunning photography travel",
    "cực đẹp":              "extremely beautiful scenic stunning photography",
    "xinh đẹp":             "beautiful charming scenic photography travel",
    "tuyệt vời":            "wonderful amazing scenic beautiful travel experience",
    "tuyệt":                "wonderful amazing scenic beautiful travel",
    "nhiều màu sắc":        "colorful vibrant photogenic aesthetic visual",
    "instagrammable":       "photogenic scenic viewpoint aesthetic colorful instagram",

    # ── English ─────────────────────────────────────────────
    "quiet":                "quiet peaceful tranquil secluded serene",
    "peaceful":             "peaceful calm serene nature gentle retreat",
    "tranquil":             "tranquil peaceful calm serene quiet nature",
    "serene":               "serene peaceful calm quiet nature",
    "secluded":             "secluded private quiet remote peaceful",
    "remote":               "remote secluded off beaten path nature quiet",
    "lively":               "lively vibrant social crowded energetic entertainment",
    "vibrant":              "vibrant lively energetic colorful urban nightlife",
    "romantic":             "romantic scenic sunset intimate couple private",
    "dreamy":               "dreamy scenic beautiful romantic atmospheric",
    "cozy":                 "cozy warm intimate comfortable indoor",
    "rustic":               "rustic traditional wooden countryside charm authentic",
    "modern":               "modern contemporary urban design sleek",
    "luxurious":            "luxury premium exclusive upscale refined",
    "picturesque":          "picturesque scenic beautiful photography worthy",
    "photogenic":           "photogenic scenic viewpoint aesthetic instagram",
    "scenic":               "scenic beautiful landscape photography outdoor",
    "beautiful":            "beautiful scenic stunning photography travel",
    "stunning":             "stunning beautiful scenic photography dramatic",
    "amazing":              "amazing wonderful scenic beautiful travel experience",
    "magical":              "magical ethereal dreamy beautiful scenic atmospheric",
    "wild":                 "wild untamed remote raw nature rugged adventure",
    "pristine":             "pristine untouched pure remote nature unspoiled",
    "dramatic":             "dramatic grand majestic vast imposing scenic",
    "fun":                  "fun lively entertaining social enjoyable activities",
    "adrenaline":           "adrenaline thrilling exciting extreme adventure outdoor",
    "relaxed":              "relaxed peaceful calm slow wellness rest nature",
    "chill":                "chill relaxed peaceful slow no rush comfortable",
    "nostalgic":            "nostalgic vintage retro old world sentimental charm",
    "colorful":             "colorful vibrant visual photography aesthetic",
    "hidden gem":           "hidden gem off beaten path discovery unique local",
    "off the beaten path":  "off beaten path remote hidden gem undiscovered",
    "off beaten path":      "off beaten path remote hidden gem undiscovered",
    "undiscovered":         "undiscovered hidden gem off beaten path unique",
    "unique":               "unique special distinctive travel experience",
    "authentic":            "authentic local traditional immersive cultural",
    "immersive":            "immersive authentic local cultural deep experience",
}

# ═════════════════════════════════════════════════════════════
# J. ACTIVITIES (free-text signals)
# ═════════════════════════════════════════════════════════════
ACTIVITIES: dict[str, str] = {
    # ── Vietnamese — water ──────────────────────────────────
    "bơi lội":              "swimming water beach pool outdoor activity",
    "bơi":                  "swimming water beach pool outdoor activity",
    "lặn biển":             "diving scuba snorkeling coral reef underwater marine",
    "lặn":                  "diving snorkeling underwater marine water activity",
    "snorkel":              "snorkeling reef tropical marine shallow water",
    "chèo kayak":           "kayaking paddle water river lake adventure",
    "kayak":                "kayaking paddle water river lake adventure",
    "chèo thuyền":          "rowing boat paddle serene water activity",
    "lướt sóng":            "surfing wave beach sport water adventure",
    "lướt ván":             "surfing wakeboard water sport adventure",
    "đi thuyền":            "boat cruise river lake scenic tour water",
    "thuyền":               "boat cruise river lake scenic water",
    "câu cá":               "fishing boat lake river local tranquil",
    "chèo sup":             "stand up paddleboard SUP water coastal calm",
    "bơi hang":             "cave swimming underground cool unique adventure",

    # ── Vietnamese — land ───────────────────────────────────
    "leo núi":              "mountain trekking hiking summit trail climbing",
    "đi bộ":                "walking hiking trail nature scenic gentle stroll",
    "trekking":             "trekking hiking mountain trail outdoor nature",
    "đi bộ đường dài":      "trekking multi day trail mountain wilderness camping",
    "leo thác":             "waterfall trekking nature trail wet adventure",
    "đạp xe":               "cycling bike ride scenic countryside road trip",
    "xe đạp":               "cycling bike scenic countryside road trip",
    "cưỡi ngựa":            "horse riding countryside outdoor scenic leisure",
    "leo vách đá":          "rock climbing sport outdoor adventure challenge",
    "zipline":              "zipline canopy adventure adrenaline outdoor",
    "cắm trại":             "camping outdoor wilderness nature campfire stars",
    "cắm trại dưới sao":    "camping stargazing outdoor wilderness nature night",
    "dã ngoại":             "picnic outdoor nature countryside fresh air relaxed",
    "đi jeep":              "jeep tour off road adventure highland rural terrain",
    "trượt cát":            "sandboarding dune sand adventure",
    "đua moto":             "motorbike trail adventure scenic rural road trip",

    # ── Vietnamese — air ────────────────────────────────────
    "dù lượn":              "paragliding aerial view adventure adrenaline scenic",
    "khinh khí cầu":        "hot air balloon aerial scenic sunrise romantic",
    "cáp treo":             "cable car aerial mountain view scenic comfortable",

    # ── Vietnamese — wellness ───────────────────────────────
    "spa":                  "spa massage wellness relaxation body treatment",
    "massage":              "massage therapy relaxation wellness muscle relief",
    "yoga":                 "yoga meditation wellness mindfulness retreat",
    "thiền":                "meditation mindfulness silent retreat wellness spiritual",
    "tắm bùn":              "mud bath mineral wellness spa relax therapeutic",
    "tắm suối khoáng":      "mineral spring thermal bath wellness relaxation",
    "tắm lá thuốc":         "herbal bath traditional wellness healing ethnic",
    "chữa lành":            "healing restorative wellness retreat peaceful nature",

    # ── Vietnamese — cultural ───────────────────────────────
    "nấu ăn":               "cooking class culinary food culture local hands on",
    "học nấu ăn":           "cooking class culinary local food culture",
    "làm gốm":              "pottery class craft hands on artisan traditional",
    "vẽ tranh":             "painting class art creative workshop cultural",
    "làm bánh":             "baking class culinary hands on local food",
    "chụp ảnh":             "photography scenic viewpoint landscape artistic",
    "ngắm chim":            "birdwatching binoculars wetland nature eco quiet",
    "xem văn nghệ":         "cultural show performance traditional evening",
    "xem múa":              "dance performance cultural show traditional",
    "mua sắm":              "shopping market souvenir boutique local",

    # ── English ─────────────────────────────────────────────
    "swimming":             "swimming water beach pool outdoor activity",
    "diving":               "diving scuba snorkeling coral reef underwater",
    "snorkeling":           "snorkeling reef tropical marine shallow water",
    "kayaking":             "kayaking paddle water river adventure",
    "surfing":              "surfing wave beach sport water adrenaline",
    "fishing":              "fishing boat tranquil river lake local",
    "boating":              "boating cruise scenic river lake water",
    "cycling":              "cycling bike scenic countryside road",
    "trekking":             "trekking hiking mountain trail outdoor nature",
    "hiking":               "hiking trail mountain nature outdoor scenic",
    "climbing":             "climbing mountain rock outdoor adventure challenge",
    "rock climbing":        "rock climbing sport outdoor adventure challenge",
    "camping":              "camping outdoor wilderness nature fire stars",
    "zip line":             "zipline canopy adventure adrenaline outdoor",
    "zipline":              "zipline canopy adventure adrenaline outdoor",
    "paragliding":          "paragliding aerial view adventure adrenaline",
    "hot air balloon":      "hot air balloon aerial scenic sunrise romantic",
    "cable car":            "cable car aerial mountain scenic comfortable",
    "photography":          "photography scenic viewpoint landscape artistic",
    "cooking class":        "cooking class culinary local food experience",
    "pottery":              "pottery class craft hands on artisan creative",
    "yoga retreat":         "yoga retreat wellness mindfulness nature peaceful",
    "meditation":           "meditation mindfulness silent retreat wellness spiritual",
    "spa":                  "spa massage wellness relaxation body treatment",
    "birdwatching":         "birdwatching nature eco wetland binoculars quiet",
    "wildlife watching":    "wildlife watching animals nature eco observation",
    "motorbike":            "motorbike scenic rural road trip adventure freedom",
    "motorbike tour":       "motorbike scenic rural road trip adventure",
    "jeep tour":            "jeep off road highland rural terrain adventure",
    "mud bath":             "mud bath mineral wellness spa therapeutic relax",
    "sandboarding":         "sandboarding dune adventure fun scenic",
    "horse riding":         "horse riding countryside outdoor scenic leisure",
    "picnic":               "picnic outdoor nature countryside relaxed gentle",
    "shopping":             "shopping market souvenir local boutique",
    "sightseeing":          "sightseeing tour guided heritage landmark cultural",
    "boat cruise":          "boat cruise scenic river lake water tour",
    "boat trip":            "boat trip cruise scenic water river lake",
    "cultural show":        "cultural show performance traditional evening",
    "food tour":            "food tour culinary street market tasting local",
}

# ═════════════════════════════════════════════════════════════
# K. FOOD & DRINK
# ═════════════════════════════════════════════════════════════
FOOD_DRINK: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "ẩm thực":              "food cuisine culinary local culture dining experience",
    "ẩm thực địa phương":   "local cuisine authentic regional food culture flavour",
    "đồ ăn":                "food dining cuisine local culinary experience",
    "ăn uống":              "dining food local cuisine restaurant tasting",
    "hải sản":              "seafood fresh fish shrimp crab ocean coastal cuisine",
    "đồ hải sản":           "seafood fresh fish shrimp crab coastal cuisine",
    "ăn hải sản":           "seafood dining fresh fish coastal ocean cuisine",
    "món chay":             "vegetarian vegan plant based healthy local",
    "ăn chay":              "vegetarian vegan plant based healthy local food",
    "đồ ăn đường phố":      "street food cheap authentic local vendor night market",
    "ăn đường phố":         "street food cheap authentic local vendor market",
    "cà phê":               "cafe coffee culture local hang out cozy",
    "uống cà phê":          "cafe coffee culture local cozy relaxed",
    "café":                 "cafe coffee culture local cozy relaxed",
    "bia":                  "beer local street social cheap authentic",
    "bia hơi":              "street beer local cheap social authentic",
    "trà":                  "tea culture highland ceremony calm relaxing",
    "uống trà":             "tea culture calm relaxing ceremony local",
    "rượu":                 "wine spirits local culture dining experience",
    "đặc sản":              "local specialty food cuisine authentic cultural",
    "đặc sản vùng miền":    "regional specialty food cuisine authentic cultural",
    "thử đặc sản":          "trying local specialty food cuisine authentic",
    "thử đồ ăn":            "trying local food cuisine tasting authentic",
    "thử ẩm thực":          "food tasting culinary tour local street market",
    "chợ":                  "market local vendor food craft shopping authentic",
    "chợ đêm":              "night market street food vendor local shopping",

    # ── English ─────────────────────────────────────────────
    "food":                 "food cuisine culinary local dining experience",
    "local food":           "local cuisine authentic regional cultural flavour",
    "street food":          "street food cheap authentic local vendor market",
    "seafood":              "seafood fresh fish shrimp crab coastal ocean",
    "vegetarian":           "vegetarian plant based healthy local food",
    "vegan":                "vegan plant based strict no animal healthy",
    "fine dining":          "fine dining gourmet upscale elegant experience",
    "coffee":               "coffee cafe culture local cozy hang out",
    "cafe":                 "cafe coffee culture local cozy relaxed",
    "restaurant":           "restaurant dining food cuisine local experience",
    "culinary":             "culinary food culture local cuisine authentic",
    "cuisine":              "cuisine food local culture authentic dining",
    "food tour":            "food tour culinary tasting local culture",
    "night market":         "night market street food local vendor evening",
    "local cuisine":        "local cuisine authentic regional cultural flavour",
    "wine":                 "wine tasting vineyard gourmet fine dining",
    "beer":                 "beer local culture social casual dining",
    "tasting":              "tasting food wine culinary local authentic",
    "cooking":              "cooking class culinary local food cultural",
}

# ═════════════════════════════════════════════════════════════
# L. ACCOMMODATION
# ═════════════════════════════════════════════════════════════
ACCOMMODATION: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "khách sạn":            "hotel comfort amenities service city",
    "resort":               "resort luxury pool beachfront amenities service",
    "villa":                "villa private pool exclusive luxury quiet",
    "homestay":             "homestay local authentic community cultural immersive",
    "nhà nghỉ":             "guesthouse budget simple local affordable",
    "hostel":               "hostel budget social backpacker community",
    "bungalow":             "bungalow tropical beach private peaceful",
    "glamping":             "glamping luxury outdoor scenic nature comfort",
    "nhà trên cây":         "treehouse unique nature adventure elevated scenic",
    "nhà thuyền":           "floating house water river lake unique local",
    "ecolodge":             "ecolodge sustainable nature immersive rustic comfort",
    "ở homestay":           "homestay local authentic community cultural immersive",
    "nghỉ dưỡng":           "resort wellness relaxation stay vacation comfort",
    "nghỉ ngơi":            "rest relaxation stay comfortable peaceful",
    "chỗ ở":                "accommodation stay lodging travel",
    "phòng view biển":      "sea view room hotel resort scenic beach coastal",
    "view núi":             "mountain view room hotel scenic highland",
    "view hồ":              "lake view room hotel scenic serene",
    "phòng đẹp":            "beautiful room hotel scenic comfortable",

    # ── English ─────────────────────────────────────────────
    "hotel":                "hotel comfort amenities service city stay",
    "guesthouse":           "guesthouse budget simple local affordable",
    "hostel":               "hostel budget social backpacker community",
    "villa":                "villa private pool exclusive luxury quiet",
    "resort":               "resort luxury pool beachfront amenities service",
    "homestay":             "homestay local authentic community cultural",
    "airbnb":               "private home local community authentic flexible stay",
    "treehouse":            "treehouse unique nature adventure elevated",
    "ecolodge":             "ecolodge sustainable nature immersive rustic",
    "cabin":                "cabin rustic nature retreat woodland cozy",
    "glamping":             "glamping luxury outdoor scenic nature comfort",
    "camping":              "camping outdoor wilderness nature tent stars",
    "boutique hotel":       "boutique hotel design intimate character local",
    "overwater bungalow":   "overwater bungalow tropical reef luxury romantic",
    "beachfront":           "beachfront hotel resort beach coastal direct access",
    "ocean view":           "ocean view hotel room coastal beach scenic",
    "sea view":             "sea view hotel room coastal beach scenic",
    "mountain view":        "mountain view hotel room highland scenic",
    "private pool":         "private pool villa luxury exclusive intimate",
    "infinity pool":        "infinity pool resort luxury scenic view",
}

# ═════════════════════════════════════════════════════════════
# M. CULTURAL & HERITAGE
# ═════════════════════════════════════════════════════════════
CULTURAL_HERITAGE: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "văn hóa":              "cultural heritage local tradition community authentic",
    "văn hóa địa phương":   "local culture heritage tradition community authentic",
    "tìm hiểu văn hóa":     "cultural discovery heritage local tradition learning",
    "lịch sử":              "history heritage monument ancient museum educational",
    "di tích lịch sử":      "historic site heritage monument ancient cultural",
    "đền":                  "shrine sacred spiritual pilgrimage heritage vietnamese",
    "chùa":                 "temple pagoda spiritual meditation Buddhism sacred",
    "đến chùa":             "temple Buddhist sacred spiritual peaceful heritage",
    "đình làng":            "communal house heritage traditional vietnamese sacred",
    "nhà thờ":              "church cathedral colonial architecture historic spiritual",
    "bảo tàng":             "museum history heritage education exhibit cultural",
    "thăm bảo tàng":        "museum visit history heritage education cultural",
    "di sản":               "heritage historic ancient architecture preservation",
    "di sản thế giới":      "world heritage UNESCO historic ancient cultural",
    "phố cổ":               "old town heritage historic architecture charming",
    "làng nghề":            "craft village artisan traditional handmade workshop",
    "làng cổ":              "ancient village heritage traditional cultural authentic",
    "lễ hội":               "festival celebration local tradition culture crowd",
    "lễ hội truyền thống":  "traditional festival celebration local culture heritage",
    "phong tục":            "local custom tradition culture authentic immersive",
    "dân tộc":              "ethnic minority culture traditional authentic heritage",
    "dân tộc thiểu số":     "ethnic minority highland culture traditional authentic",
    "người dân tộc":        "ethnic minority people highland culture traditional",
    "nghề thủ công":        "handicraft artisan traditional cultural authentic",
    "thủ công mỹ nghệ":     "handicraft souvenir traditional artisan shop",

    # ── English ─────────────────────────────────────────────
    "cultural":             "cultural heritage local tradition community authentic",
    "culture":              "culture heritage tradition local experience community",
    "heritage":             "heritage historic ancient architecture preservation",
    "history":              "history ancient monument heritage educational museum",
    "historical":           "historical heritage monument ancient museum educational",
    "temple":               "temple spiritual sacred meditation heritage",
    "pagoda":               "pagoda Buddhist sacred spiritual peaceful heritage",
    "museum":               "museum history heritage education exhibit cultural",
    "old town":             "old town heritage historic charming architecture",
    "ancient":              "ancient heritage historic monument museum cultural",
    "traditional":          "traditional heritage cultural local craft festival",
    "ethnic":               "ethnic culture traditional authentic heritage minority",
    "local culture":        "local culture heritage tradition community authentic",
    "festival":             "festival celebration local tradition crowd cultural",
    "craft village":        "craft village artisan traditional handmade workshop",
    "handicraft":           "handicraft artisan traditional cultural souvenir",
    "art":                  "art gallery creative museum exhibition cultural",
    "architecture":         "architecture design landmark historic building",
    "colonial":             "colonial architecture heritage elegant historic period",
    "pilgrimage":           "pilgrimage sacred spiritual religious heritage holy",
    "ritual":               "ritual cultural traditional heritage local authentic",
    "ceremony":             "ceremony cultural traditional local heritage authentic",
    "UNESCO":               "UNESCO world heritage historic cultural ancient",
}

# ═════════════════════════════════════════════════════════════
# N. WELLNESS & HEALTH
# ═════════════════════════════════════════════════════════════
WELLNESS_HEALTH: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "nghỉ dưỡng":           "wellness resort relaxation vacation rest healing nature",
    "phục hồi sức khỏe":    "health recovery wellness relaxation healing nature resort",
    "chữa bệnh":            "healing medical wellness treatment health recovery",
    "chữa lành tâm hồn":    "soul healing wellness retreat peaceful nature mindfulness",
    "lấy lại sức":          "recover energy wellness relaxation rest healing",
    "tái tạo năng lượng":   "recharge energy wellness relaxation healing retreat",
    "detox":                "detox cleanse wellness healthy retreat nature",
    "thanh lọc":            "cleanse detox wellness healthy retreat nature",
    "thư giãn đầu óc":      "mental relaxation wellness mindfulness peaceful nature",
    "tĩnh tâm":             "mindfulness meditation peaceful retreat wellness spiritual",
    "cân bằng":             "balance wellness mindfulness peaceful healing nature",
    "bình tĩnh":            "calm peaceful mindfulness wellness balanced nature",
    "sức khỏe":             "health wellness fitness outdoor nature active",
    "tốt cho sức khỏe":     "healthy wellness fitness outdoor nature beneficial",

    # ── English ─────────────────────────────────────────────
    "wellness":             "wellness spa healing retreat peaceful slow nature",
    "wellness retreat":     "wellness spa healing retreat peaceful nature mindfulness",
    "healing":              "healing restorative wellness retreat nature peaceful",
    "detox":                "detox cleanse wellness healthy retreat nature",
    "mindfulness":          "mindfulness meditation peaceful wellness nature retreat",
    "meditation retreat":   "meditation retreat mindfulness silent spiritual wellness",
    "yoga retreat":         "yoga retreat wellness mindfulness nature peaceful",
    "spa retreat":          "spa retreat wellness relaxation massage therapy",
    "health":               "health wellness fitness outdoor nature active",
    "healthy":              "healthy wellness fitness outdoor nature beneficial",
    "recharge":             "recharge energy wellness relaxation healing retreat",
    "rejuvenate":           "rejuvenate wellness relaxation healing retreat peaceful",
    "restore":              "restore wellness relaxation healing peaceful retreat",
    "refresh":              "refresh wellness relaxation peaceful nature healing",
    "recovery":             "recovery wellness rest relaxation healing nature",
    "mental health":        "mental health wellness mindfulness peaceful nature retreat",
    "self care":            "self care wellness spa relaxation healing retreat",
    "self-care":            "self care wellness spa relaxation healing retreat",
    "burnout recovery":     "burnout recovery wellness retreat rest healing peaceful",
}

# ═════════════════════════════════════════════════════════════
# O. PHOTOGRAPHY & CONTENT
# ═════════════════════════════════════════════════════════════
PHOTOGRAPHY_CONTENT: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "chụp ảnh":             "photography scenic viewpoint landscape artistic",
    "chụp hình":            "photography scenic viewpoint landscape artistic",
    "check-in":             "photogenic scenic viewpoint instagram aesthetic",
    "điểm check-in":        "photogenic scenic viewpoint instagram aesthetic landmark",
    "điểm check-in đẹp":    "beautiful photogenic scenic viewpoint instagram aesthetic",
    "quay phim":            "videography scenic drone cinematic landscape",
    "quay video":           "videography scenic cinematic landscape content",
    "cảnh đẹp để chụp":     "scenic photogenic viewpoint photography beautiful landscape",
    "cảnh sống ảo":         "instagram worthy aesthetic photogenic colorful unique",
    "góc sống ảo":          "instagram worthy aesthetic photogenic viewpoint unique",
    "ảnh đẹp":              "beautiful photography scenic aesthetic viewpoint",
    "ảnh sống ảo":          "instagram photography aesthetic scenic photogenic",
    "máy ảnh":              "photography camera scenic landscape artistic",
    "flycam":               "drone aerial photography scenic landscape cinematic",
    "drone":                "drone aerial photography scenic landscape cinematic",

    # ── English ─────────────────────────────────────────────
    "photography":          "photography scenic viewpoint landscape artistic",
    "instagram":            "instagram worthy photogenic colorful aesthetic scenic",
    "instagrammable":       "instagram photogenic colorful aesthetic scenic viewpoint",
    "content creation":     "content creator photography videography aesthetic scenic",
    "drone shot":           "drone aerial photography scenic landscape cinematic",
    "golden hour":          "golden hour photography sunrise sunset scenic warm",
    "landscape photography":"landscape scenic nature photography dramatic wide",
    "photo spot":           "photo spot photogenic scenic viewpoint aesthetic",
    "photo opportunity":    "photography scenic viewpoint beautiful opportunity",
    "scenic views":         "scenic views beautiful photography landscape outdoor",
    "viewpoint":            "viewpoint scenic photography landscape panoramic",
}

# ═════════════════════════════════════════════════════════════
# MASTER REGISTRY
# ═════════════════════════════════════════════════════════════
ALL_CONTEXT: dict[str, str] = {
    **SEASON_WEATHER,
    **SOCIAL_GROUP,
    **TRIP_DURATION,
    **TRIP_DISTANCE,
    **BUDGET_LEVEL,
    **PACE,
    **NATURE_LANDSCAPE,
    **TRAVEL_INTENT,
    **MOOD_ATMOSPHERE,
    **ACTIVITIES,
    **FOOD_DRINK,
    **ACCOMMODATION,
    **CULTURAL_HERITAGE,
    **WELLNESS_HEALTH,
    **PHOTOGRAPHY_CONTENT,
}