"""
maps/emotions.py
================
Maps emotional states and mental vibes to travel experience keywords.
Translates "how the user feels" into "what kind of trip they need".

This mapping allows the preprocessor to capture subtle sentiment from
user-written text and convert it into high-value embedding dimensions.

Duplicate and substring keys are intentional — longer phrases carry
stronger, more specific signals and produce better embedding alignment.

─────────────────────────────────────────────────────────────
SECTION INDEX
─────────────────────────────────────────────────────────────
  A. EXHAUSTION & STRESS      — restorative, slow, spa, nature
  B. BOREDOM & STAGNATION     — stimulating, adventure, variety
  C. SADNESS & LONELINESS     — uplifting, social, healing, scenic
  D. ROMANCE & INTIMACY       — couple, sunset, private, luxury
  E. CURIOSITY & LEARNING     — cultural, heritage, educational
  F. EXCITEMENT & THRILL      — adrenaline, extreme, active
  G. NOSTALGIA & HERITAGE     — vintage, traditional, old-town
  H. SOCIAL FATIGUE           — solo, secluded, off-grid, quiet
  I. JOY & CELEBRATION        — festive, fun, happy, party
  J. FREEDOM & ESCAPE         — liberation, open road, wild
  K. SPIRITUAL & MINDFULNESS  — sacred, inner peace, retreat
  L. FAMILY LOVE & BONDING    — warmth, togetherness, children

IMPLEMENTATION NOTES
──────────────────────────────────────────────────────────────
  • Longer phrases take priority over shorter overlapping ones via
    _dedupe_substrings in registry.py (longest match wins).
  • Emotional values are biased toward positive/solution-oriented travel.
  • Vietnamese and English keys are both first-class entries.
──────────────────────────────────────────────────────────────
"""

# ═════════════════════════════════════════════════════════════
# A. EXHAUSTION & STRESS
# ═════════════════════════════════════════════════════════════
EXHAUSTION_STRESS: dict[str, str] = {
    # ── Vietnamese — core ───────────────────────────────────
    "mệt mỏi":                  "relaxation travel spa resort rest wellness recovery experience",
    "mệt quá":                  "deep rest travel wellness spa recovery resort peaceful",
    "mệt lắm":                  "deep rest travel wellness spa recovery resort peaceful",
    "rất mệt":                  "deep rest travel wellness spa secluded recovery nature",
    "quá mệt":                  "deep rest travel spa wellness secluded resort recovery",
    "mệt mỏi quá":              "deep rest travel wellness spa secluded recovery nature",
    "người mệt mỏi":            "spa resort travel rest wellness slow experience nature",
    "kiệt sức":                 "deep rest travel wellness spa secluded resort recovery",
    "kiệt lực":                 "deep rest travel resort spa wellness recovery nature",
    "kiệt quệ":                 "deep rest travel wellness spa secluded recovery nature",
    "cạn sức":                  "deep rest travel wellness resort recovery nature spa",
    "mệt đuối":                 "deep rest travel spa wellness secluded resort recovery",
    "uể oải":                   "light travel nature walking gentle activities fresh air",
    "uể oải lắm":               "gentle slow travel nature fresh air walking relaxation",
    "lờ đờ":                    "gentle slow travel nature fresh air rest relaxation",
    "lơ mơ":                    "gentle slow travel rest nature peaceful relaxation",
    "căng thẳng":               "relaxation travel nature peaceful meditation wellness retreat",
    "rất căng thẳng":           "deep relaxation travel nature peaceful meditation wellness retreat",
    "căng thẳng quá":           "escape travel nature secluded quiet retreat stress relief",
    "căng thẳng lắm":           "escape travel nature secluded quiet retreat stress relief",
    "bị stress":                "relaxation travel nature wellness meditation peaceful retreat",
    "đang stress":              "relaxation travel nature wellness meditation peaceful retreat",
    "stress nặng":              "deep relaxation travel nature secluded spa wellness retreat",
    "stress quá":               "escape travel nature secluded quiet retreat stress relief",
    "áp lực":                   "escape travel nature secluded quiet retreat stress relief",
    "áp lực cao":               "escape travel secluded nature retreat mindfulness peaceful",
    "áp lực lớn":               "escape travel secluded nature retreat mindfulness peaceful",
    "áp lực công việc":         "work escape travel nature wellness retreat peaceful relaxation",
    "chịu áp lực":              "escape travel nature secluded retreat stress relief wellness",
    "lo lắng":                  "calm travel nature serene meditation mindfulness peaceful",
    "lo lắng nhiều":            "calm travel nature serene meditation mindfulness peaceful",
    "hay lo lắng":              "calm serene travel nature mindfulness peaceful retreat",
    "bồn chồn":                 "calm travel quiet nature walking meditation peaceful",
    "quá tải":                  "escape travel off grid nature quiet secluded retreat",
    "bị quá tải":               "escape travel off grid nature quiet secluded retreat",
    "mất ngủ":                  "calm travel serene nature spa rest wellness retreat",
    "không ngủ được":           "calm travel quiet nature spa rest wellness retreat",
    "khó ngủ":                  "calm travel serene nature spa rest wellness retreat peaceful",
    "thiếu ngủ":                "rest travel peaceful quiet nature spa recovery",
    "đau đầu":                  "quiet travel nature fresh air spa wellness peaceful",
    "đầu nặng":                 "fresh air travel outdoor nature scenic quiet spa",
    "đầu óc mệt mỏi":          "mental rest travel nature quiet spa wellness peaceful",
    "tâm lý nặng":              "meditation travel retreat nature quiet mindfulness peaceful",
    "tâm lý căng":              "relaxation travel nature peaceful meditation wellness retreat",
    "ngộp thở":                 "escape travel open nature fresh air outdoor peaceful",
    "ngột ngạt":                "escape travel open nature fresh air outdoor breathing space",
    "bức bối":                  "escape travel open outdoor nature fresh air free",
    "chán việc":                "escape travel adventure outdoor discovery new experience",
    "mệt vì công việc":         "work escape travel rest nature wellness peaceful recovery",
    "làm việc quá nhiều":       "overwork escape travel rest nature wellness recovery peaceful",
    "cần nghỉ":                 "relaxation travel rest resort peaceful slow experience",
    "cần nghỉ ngơi":            "relaxation travel rest resort peaceful slow nature experience",
    "cần được nghỉ":            "relaxation travel rest resort peaceful slow nature",
    "muốn nghỉ":                "resort travel beach quiet peaceful rest nature",
    "muốn nghỉ ngơi":          "resort travel beach quiet peaceful rest wellness nature",
    "cần đổi gió":              "new experience travel discovery outdoor fresh exploration",
    "muốn đổi gió":             "new experience travel discovery outdoor fresh exploration",
    "cần thay đổi không khí":   "fresh air new environment travel discovery outdoor peaceful",
    "cần xa":                   "escape travel remote nature secluded off grid retreat",
    "muốn thoát":               "escape travel remote nature secluded off grid retreat",
    "muốn thoát khỏi":          "escape travel remote nature secluded off grid retreat",
    "thoát ly":                 "escape travel adventure outdoor discovery new experience",
    "muốn trốn":                "escape travel remote nature secluded off grid retreat",
    "trốn thoát":               "escape travel remote nature secluded quiet retreat",
    "thư giãn":                 "relaxation travel spa wellness peaceful resort experience",
    "cần thư giãn":             "relaxation travel spa wellness peaceful resort nature",
    "muốn thư giãn":            "relaxation travel spa wellness peaceful resort nature",
    "nghỉ ngơi":                "rest travel resort peaceful nature quiet experience",
    "cần nghỉ xã hội":          "retreat quiet nature secluded solo off grid wellness",
    "suy nhược":                "gentle travel wellness spa recovery rest nature",
    "hao mòn":                  "rest travel recovery wellness resort nature",
    "xuống dốc":                "recovery travel rest nature wellness resort spa",
    "muốn yên":                 "quiet peaceful travel nature secluded retreat spa",
    "cần yên":                  "quiet peaceful travel nature secluded retreat spa",
    "mệt trí":                  "mental rest travel retreat nature quiet mindfulness peaceful",

    # ── English — core ──────────────────────────────────────
    "exhausted":                "spa travel wellness resort secluded rest recovery",
    "so exhausted":             "deep rest travel wellness spa secluded resort recovery",
    "totally exhausted":        "deep rest travel wellness spa secluded resort recovery",
    "completely exhausted":     "deep rest travel wellness spa secluded resort recovery",
    "burned out":               "deep rest travel wellness retreat nature slow experience",
    "burnt out":                "spa travel wellness nature secluded recovery retreat",
    "burning out":              "rest travel wellness nature secluded retreat spa",
    "severe burnout":           "deep rest travel wellness nature secluded retreat spa",
    "feeling tired":            "relaxation travel resort beach quiet rest",
    "so tired":                 "deep rest travel wellness spa recovery resort peaceful",
    "really tired":             "deep rest travel wellness spa recovery resort peaceful",
    "very tired":               "deep rest travel wellness spa recovery resort peaceful",
    "tired":                    "relaxation travel spa rest wellness peaceful resort",
    "drained":                  "nature travel retreat wellness calm recovery peaceful",
    "completely drained":       "deep rest travel nature retreat wellness calm recovery",
    "stressed":                 "relaxation travel spa nature retreat peaceful wellness meditation",
    "very stressed":            "deep relaxation travel spa nature retreat peaceful wellness",
    "stressed out":             "escape travel spa nature retreat peaceful wellness meditation",
    "highly stressed":          "escape travel spa nature secluded retreat wellness",
    "work stress":              "work escape travel rest nature wellness peaceful recovery",
    "anxious":                  "calm travel serene nature meditation mindfulness peaceful",
    "feeling anxious":          "calm travel serene nature meditation mindfulness peaceful",
    "overwhelmed":              "escape travel secluded quiet nature off grid retreat",
    "feeling overwhelmed":      "escape travel secluded quiet nature off grid retreat",
    "totally overwhelmed":      "deep escape travel secluded quiet nature off grid retreat",
    "tense":                    "spa travel wellness relaxation peaceful",
    "on edge":                  "peaceful travel nature quiet retreat mindfulness",
    "fatigued":                 "rest travel resort quiet beach gentle wellness",
    "mental fatigue":           "meditation travel retreat nature quiet mindfulness spa",
    "mental exhaustion":        "deep rest travel nature quiet spa mindfulness wellness retreat",
    "worn out":                 "recovery travel rest resort peaceful nature spa",
    "totally worn out":         "deep recovery travel rest resort spa secluded nature",
    "overworked":               "escape travel retreat wellness nature rest spa",
    "need a break":             "short trip travel getaway nature rest peaceful",
    "need rest":                "spa travel resort quiet beach wellness rest",
    "need to rest":             "spa travel resort quiet beach wellness rest",
    "desperately need a break": "escape travel secluded nature spa wellness retreat rest",
    "recharge":                 "nature travel retreat spa wellness peaceful recovery",
    "need to recharge":         "nature travel retreat spa wellness peaceful recovery",
    "no energy":                "slow travel peaceful resort rest gentle nature",
    "low energy":               "slow gentle travel peaceful resort rest nature",
    "run down":                 "wellness spa travel recovery resort rest quiet",
    "frazzled":                 "spa travel retreat quiet nature peaceful rest wellness",
    "depleted":                 "deep rest travel resort nature wellness recovery spa",
    "weary":                    "slow travel peaceful resort spa quiet nature",
    "wrecked":                  "deep rest travel secluded spa wellness recovery nature",
    "burnout":                  "deep rest travel wellness nature secluded retreat spa",
    "spent":                    "rest travel resort spa quiet nature recovery",
    "numb":                     "nature travel scenic peaceful uplifting wellness retreat",
    "disconnected":             "community travel local social scenic peaceful experience",
    "lethargic":                "slow gentle travel peaceful resort spa rest nature",
    "sluggish":                 "rest travel gentle nature quiet spa wellness",
    "fried":                    "deep rest travel secluded spa wellness recovery nature",
    "zapped":                   "rest travel recovery wellness resort spa nature",
    "wiped out":                "deep rest travel spa secluded recovery resort wellness",
    "worn thin":                "escape travel retreat nature rest wellness peaceful",
    "need vacation":            "resort travel beach peaceful rest nature getaway",
    "need a vacation":          "resort travel beach peaceful rest nature getaway",
    "lifeless":                 "nature travel scenic uplifting vibrant recovery",
    "at capacity":              "escape travel secluded nature off grid quiet retreat",
    "hollow":                   "nature travel scenic community uplifting peaceful",
    "running on empty":         "deep rest travel wellness spa nature secluded recovery",
    "at breaking point":        "escape travel secluded nature spa wellness retreat rest",
}

# ═════════════════════════════════════════════════════════════
# B. BOREDOM & STAGNATION
# ═════════════════════════════════════════════════════════════
BOREDOM: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "nhàm chán":                "entertainment travel activities nightlife adventure variety stimulating",
    "quá nhàm chán":            "vibrant travel lively entertainment variety stimulating adventure",
    "nhàm chán quá":            "vibrant travel lively entertainment variety stimulating adventure",
    "chán ngán":                "vibrant entertainment travel variety unique stimulating experience",
    "chán lắm":                 "vibrant travel lively entertainment variety stimulating adventure",
    "buồn tẻ":                  "vibrant travel lively entertainment variety unique experience",
    "tẻ nhạt":                  "stimulating travel discovery adventure entertainment variety",
    "đơn điệu":                 "variety travel unique discovery adventure stimulating lively",
    "lặp lại":                  "discovery travel unique variety new experience change",
    "cứ lặp đi lặp lại":        "new experience travel variety unique discovery adventure",
    "ngán ngẩm":                "new experience travel discovery unique adventure variety stimulating",
    "thờ ơ":                    "vibrant travel lively colorful stimulating adventure discovery",
    "vô cảm":                   "uplifting travel vibrant scenic colorful stimulating new",
    "vô vị":                    "vibrant travel colorful lively stimulating entertainment",
    "thiếu hứng":               "vibrant travel discovery adventure lively stimulating colorful",
    "thiếu động lực":           "adventure travel outdoor discovery stimulating variety active",
    "không có hứng":            "vibrant travel discovery lively entertainment stimulating colorful",
    "thiếu cảm xúc":            "vibrant travel adventure new experience colorful stimulating",
    "thiếu cảm hứng":           "scenic travel cultural art discovery vibrant stimulating",
    "không hứng thú":           "vibrant travel discovery stimulating lively adventure colorful",
    "mới mẻ":                   "new experience travel discovery unique adventure stimulating",
    "muốn mới mẻ":              "new experience travel discovery unique adventure stimulating",
    "cần gì đó mới":            "new experience travel discovery unique adventure stimulating",
    "cần thay đổi":             "new experience travel discovery stimulating change variety",
    "muốn thay đổi":            "new experience travel discovery stimulating change variety",
    "tìm kiếm":                 "exploration travel discovery adventure outdoor cultural experience",
    "kích thích":               "adventure travel adrenaline outdoor stimulating activities sport",
    "phiêu lưu":                "adventure travel outdoor trekking discovery bold exploration",
    "muốn đi phiêu lưu":        "adventure travel outdoor trekking discovery bold exploration",
    "muốn trải":                "new experience travel cultural authentic local immersive",
    "trơ trọi":                 "vibrant travel colorful lively stimulating social entertainment",
    "không hứng thú":           "vibrant travel discovery stimulating lively adventure colorful",
    "cần vui":                  "fun travel lively cheerful social entertainment activities",
    "buồn":                     "uplifting travel vibrant cheerful colorful fun social activities",

    # ── English ─────────────────────────────────────────────
    "bored":                    "entertainment travel activities nightlife adventure variety stimulating",
    "so bored":                 "vibrant travel lively entertainment adventure variety stimulating",
    "really bored":             "vibrant travel lively entertainment adventure variety stimulating",
    "terribly bored":           "vibrant travel lively entertainment adventure variety stimulating",
    "boredom":                  "entertainment travel activities variety stimulating adventure",
    "stagnant":                 "new experience travel discovery stimulating vibrant adventure",
    "feeling stagnant":         "new experience travel discovery stimulating vibrant adventure",
    "stuck in a rut":           "new experience travel offbeat discovery unique adventure",
    "in a rut":                 "new experience travel offbeat discovery unique adventure",
    "monotonous":               "variety travel unique discovery adventure stimulating",
    "life is monotonous":       "new experience travel variety discovery adventure stimulating",
    "dull":                     "vibrant travel colorful lively entertainment adventure",
    "flat":                     "vibrant travel lively colorful energetic stimulating activities",
    "restless":                 "adventure travel outdoor active discovery exploration new",
    "feeling restless":         "adventure travel outdoor active discovery exploration new",
    "listless":                 "vibrant travel outdoor active discovery new experience",
    "jaded":                    "unique travel hidden gem offbeat authentic discovery",
    "idle":                     "active travel outdoor adventure discovery sport variety",
    "apathetic":                "vibrant travel lively outdoor active discovery new experience",
    "disengaged":               "adventure travel outdoor stimulating discovery cultural new",
    "unmotivated":              "adventure travel discovery outdoor stimulating variety active",
    "tedious":                  "vibrant travel unique discovery adventure variety stimulating",
    "stale":                    "fresh travel new experience discovery offbeat unique",
    "same old":                 "new experience travel offbeat discovery unique hidden gem",
    "same old same old":        "new experience travel offbeat discovery unique hidden gem",
    "repetitive":               "variety travel discovery adventure unique stimulating new",
    "going nowhere":            "new experience travel discovery adventure change stimulating",
    "need change":              "new experience travel discovery stimulating change variety",
    "need something new":       "new experience travel discovery unique adventure stimulating",
    "craving something new":    "unique travel discovery new experience offbeat hidden gem",
    "craving new":              "unique travel discovery new experience offbeat hidden gem",
    "need excitement":          "adventure travel adrenaline vibrant lively entertainment sport",
    "need adventure":           "adventure travel trekking outdoor adrenaline sport exploration",
    "in a funk":                "uplifting travel vibrant colorful lively adventure outdoor",
    "no spark":                 "vibrant travel colorful adventure lively stimulating outdoor",
    "uninspired":               "scenic travel beautiful art cultural discovery vibrant",
    "purposeless":              "meaningful travel cultural nature discovery community authentic",
    "unexcited":                "adventure travel vibrant stimulating colorful lively outdoor",
    "adventure":                "adventure travel trekking outdoor adrenaline sport exploration",
    "excitement":               "adventure travel adrenaline vibrant lively entertainment sport",
    "to explore":               "exploration travel discovery outdoor cultural adventure new",
}

# ═════════════════════════════════════════════════════════════
# C. SADNESS & LONELINESS
# ═════════════════════════════════════════════════════════════
SADNESS: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "đang buồn":                "uplifting travel scenic colorful cheerful vibrant experience",
    "buồn lắm":                 "uplifting travel scenic colorful cheerful vibrant warm social",
    "buồn quá":                 "uplifting travel scenic colorful cheerful vibrant social",
    "rất buồn":                 "uplifting travel scenic beautiful colorful cheerful healing",
    "cảm thấy buồn":            "uplifting travel scenic colorful cheerful vibrant",
    "nặng nề":                  "light travel cheerful colorful scenic uplifting healing",
    "u uất":                    "scenic travel peaceful healing nature uplifting beautiful",
    "bi quan":                  "uplifting travel inspiring scenic beautiful vibrant colorful",
    "ủ rũ":                     "uplifting travel cheerful colorful vibrant lively scenic",
    "chán nản":                 "new experience travel discovery adventure vibrant stimulating",
    "tâm trạng xấu":            "uplifting travel cheerful vibrant colorful scenic festival",
    "tâm trạng không tốt":      "uplifting travel cheerful vibrant scenic colorful healing",
    "cô đơn":                   "social travel community lively festival crowd people warm",
    "cô đơn lắm":               "social travel community lively festival local warm people",
    "rất cô đơn":               "social travel community lively local warm people connection",
    "cảm thấy cô đơn":          "social travel community lively festival people warm",
    "cô quạnh":                 "social travel community lively festival local people warm",
    "trống rỗng":               "vibrant travel lively social cultural discovery experience",
    "cảm thấy trống rỗng":      "vibrant travel lively social warm cultural discovery",
    "nhớ nhà":                  "cozy travel warm local community comfort familiar",
    "xa nhà":                   "cozy travel warm local community comfort familiar",
    "nhớ gia đình":             "family warmth cozy travel community comfort familiar bonding",
    "đau khổ":                  "healing travel scenic peaceful beautiful gentle nature",
    "tổn thương":               "healing travel scenic peaceful beautiful gentle nature",
    "thất vọng":                "uplifting travel scenic colorful cheerful vibrant new experience",
    "chữa lành":                "healing travel wellness spa nature peaceful scenic retreat",
    "muốn chữa lành":           "healing travel wellness spa nature peaceful scenic retreat",
    "cần chữa lành":            "healing travel wellness spa nature peaceful scenic retreat",
    "chữa lành vết thương":     "healing restorative travel wellness spa nature peaceful retreat",
    "lạc lối":                  "discovery travel self exploration solo nature peaceful scenic",
    "mất phương hướng":         "discovery travel self exploration nature solo peaceful scenic",
    "quên đi":                  "adventure travel stimulating vibrant discovery new experience",
    "muốn quên":                "adventure travel stimulating vibrant discovery new experience",
    "kết nối":                  "community travel local social festival people cultural warm",
    "muốn kết nối":             "community travel local social festival people warm cultural",
    "thiếu bạn":                "social travel community lively festival crowd friends warm",
    "cần chia sẻ":              "social travel community local people cultural warm authentic",
    "chìm đắm":                 "uplifting travel vibrant scenic colorful healing nature",
    "nước mắt":                 "healing travel peaceful scenic nature beautiful gentle",
    "khóc":                     "healing travel peaceful scenic beautiful gentle nature",

    # ── English ─────────────────────────────────────────────
    "sad":                      "uplifting travel scenic beautiful colorful cheerful healing",
    "feeling sad":              "uplifting travel scenic beautiful colorful cheerful",
    "very sad":                 "uplifting healing travel scenic beautiful colorful cheerful",
    "deeply sad":               "healing travel scenic peaceful nature beautiful uplifting",
    "unhappy":                  "uplifting travel scenic cheerful colorful vibrant festival",
    "miserable":                "uplifting travel colorful vibrant cheerful scenic festival",
    "down":                     "cheerful travel colorful vibrant warm social uplifting",
    "feeling down":             "cheerful uplifting travel colorful vibrant warm social",
    "really down":              "uplifting healing travel colorful vibrant warm social",
    "low":                      "uplifting travel cheerful scenic colorful vibrant warm",
    "feeling low":              "uplifting travel cheerful scenic colorful vibrant entertainment",
    "in a low place":           "uplifting healing travel scenic colorful vibrant cheerful",
    "depressed":                "uplifting travel nature vibrant cheerful scenic community",
    "feeling depressed":        "uplifting travel nature vibrant cheerful scenic community",
    "lonely":                   "social travel community festival crowd lively people warm",
    "feeling lonely":           "social travel community festival crowd warm lively people",
    "very lonely":              "social travel community warm lively festival local people",
    "terribly lonely":          "social travel community warm lively festival local people",
    "alone and lonely":         "social community travel warm lively festival local people",
    "empty":                    "vibrant travel lively social cultural stimulating experience",
    "feeling empty":            "vibrant travel lively social warm cultural stimulating",
    "heartbroken":              "scenic travel peaceful healing nature beautiful gentle",
    "heartache":                "scenic travel peaceful healing nature beautiful gentle",
    "heartbreak":               "healing travel scenic peaceful nature beautiful gentle",
    "broken heart":             "healing travel scenic peaceful beautiful nature gentle",
    "melancholy":               "scenic travel beautiful gentle nature peaceful artistic",
    "grieving":                 "peaceful travel healing nature serene quiet gentle",
    "grief":                    "peaceful healing travel nature serene quiet gentle",
    "lost":                     "self discovery travel solo nature peaceful scenic exploration",
    "feeling lost":             "self discovery travel solo nature peaceful scenic exploration",
    "healing":                  "healing travel wellness spa nature peaceful scenic retreat",
    "need healing":             "healing travel wellness spa nature peaceful scenic retreat",
    "going through a breakup":  "healing solo travel scenic peaceful nature wellness retreat",
    "after a breakup":          "healing solo travel scenic peaceful nature wellness",
    "homesick":                 "cozy travel warm community local familiar comfort",
    "missing home":             "cozy travel familiar warm local community comfort",
    "missing family":           "family warmth cozy travel community comfort familiar bonding",
    "connection":               "social travel community local festival people warm culture",
    "need connection":          "social travel community local festival people warm culture",
    "isolated":                 "social travel community festival local people lively warm",
    "feeling isolated":         "social community travel warm lively festival local people",
    "abandoned":                "cozy warm community travel local social friendly",
    "need comfort":             "cozy warm travel local community familiar gentle scenic",
    "sorrowful":                "scenic travel peaceful healing beautiful nature gentle",
    "tearful":                  "healing travel scenic peaceful nature beautiful gentle",
    "desolate":                 "community travel social local festival lively warm people",
    "forlorn":                  "warm cozy travel local community comfort familiar",
    "aching":                   "scenic travel peaceful healing nature beautiful gentle",
    "broken":                   "healing travel wellness spa nature peaceful scenic",
    "gloomy":                   "uplifting travel colorful scenic vibrant cheerful outdoor",
    "hurt":                     "healing travel peaceful scenic nature beautiful gentle",
    "wounded":                  "healing travel nature scenic peaceful beautiful wellness",
    "hopeless":                 "inspiring travel scenic beautiful nature vibrant uplifting",
    "not okay":                 "uplifting healing travel scenic colorful warm community",
    "going through a hard time": "healing uplifting travel scenic peaceful nature wellness retreat",
    "tough time":               "healing uplifting travel scenic peaceful nature wellness",
}

# ═════════════════════════════════════════════════════════════
# D. ROMANCE & INTIMACY
# ═════════════════════════════════════════════════════════════
ROMANCE: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "lãng mạn":                 "romantic travel sunset couple candlelight scenic private intimate",
    "rất lãng mạn":             "very romantic travel luxury sunset couple private scenic intimate",
    "muốn lãng mạn":            "romantic travel sunset couple private scenic intimate experience",
    "kỷ niệm":                  "romantic travel special anniversary couple scenic experience",
    "kỷ niệm tình yêu":         "anniversary romantic travel couple special scenic luxury",
    "kỷ niệm ngày cưới":        "anniversary wedding romantic couple luxury scenic private",
    "trăng mật":                "honeymoon travel luxury romantic private resort scenic experience",
    "đi trăng mật":             "honeymoon travel luxury romantic private resort scenic experience",
    "du lịch trăng mật":        "honeymoon travel luxury romantic private resort scenic experience",
    "tuần trăng mật":           "honeymoon travel luxury romantic private resort scenic experience",
    "mới cưới":                 "honeymoon couple romantic private luxury resort scenic",
    "vừa cưới":                 "honeymoon couple romantic private luxury resort scenic",
    "tình cảm":                 "romantic travel intimate scenic private couple",
    "gần nhau":                 "intimate travel couple romantic scenic private quiet",
    "bên nhau":                 "couple travel intimate private scenic romantic peaceful",
    "cùng nhau":                "couple travel intimate private scenic romantic peaceful",
    "hai đứa":                  "couple travel intimate private scenic romantic",
    "hai đứa mình":             "couple travel intimate private scenic romantic",
    "ngày cưới":                "anniversary wedding romantic couple luxury scenic private",
    "cầu hôn":                  "proposal scenic viewpoint private romantic sunset luxury",
    "gắn kết":                  "romantic travel intimate private scenic couple quiet",
    "người yêu":                "romantic travel couple scenic private intimate sunset",
    "cùng người yêu":           "romantic travel couple scenic private intimate sunset",
    "tình yêu":                 "romantic travel couple scenic intimate private sunset",
    "yêu nhau":                 "romantic travel private scenic couple intimate luxury",
    "đang yêu":                 "romantic travel couple scenic intimate private beautiful",
    "yêu":                      "romantic travel couple scenic private intimate sunset",
    "hẹn hò":                   "romantic travel date scenic private couple intimate experience",
    "đi hẹn hò":                "romantic travel date scenic private couple intimate",
    "buổi hẹn hò":              "romantic travel date scenic private couple intimate dinner",
    "đêm lãng mạn":             "romantic travel candlelight sunset scenic private couple",
    "bữa tối lãng mạn":         "romantic dinner travel candlelight scenic private couple",
    "vợ chồng mới":             "honeymoon travel romantic luxury private resort scenic",
    "tặng quà":                 "romantic travel special luxury scenic private couple",
    "bất ngờ":                  "romantic travel special scenic private couple luxury",
    "surprise":                 "romantic travel special scenic private couple luxury",
    "tâm sự":                   "intimate travel private quiet scenic couple peaceful",
    "thích nhau":               "romantic couple travel scenic private intimate",
    "ấm áp":                    "romantic travel intimate warm cozy couple private scenic",
    "ngọt ngào":                "romantic travel intimate private scenic couple gentle",
    "tình nhân":                "romantic travel couple scenic private intimate sunset",
    "hẹn ước":                  "romantic travel couple scenic private intimate promise",
    "tình nhớ":                 "romantic travel scenic beautiful intimate couple private",

    # ── English ─────────────────────────────────────────────
    "romantic":                 "romantic travel sunset couple private intimate scenic experience",
    "so romantic":              "very romantic travel luxury sunset couple private scenic intimate",
    "looking for romance":      "romantic travel sunset couple private scenic intimate experience",
    "anniversary":              "romantic travel special scenic luxury private couple",
    "anniversary trip":         "anniversary romantic couple special scenic luxury travel",
    "wedding anniversary":      "anniversary wedding romantic couple luxury scenic private",
    "honeymoon":                "honeymoon travel luxury romantic private resort scenic",
    "on our honeymoon":         "honeymoon travel luxury romantic private resort scenic",
    "honeymoon trip":           "honeymoon travel luxury romantic private resort scenic",
    "proposal":                 "proposal scenic viewpoint private romantic sunset luxury",
    "planning to propose":      "proposal scenic viewpoint private romantic sunset luxury",
    "valentine":                "romantic travel couple scenic private luxury sunset",
    "valentines day":           "romantic travel couple scenic private luxury sunset",
    "date":                     "romantic travel scenic intimate private couple dinner",
    "date night":               "romantic dinner travel candlelight scenic private couple",
    "in love":                  "romantic travel scenic intimate private couple sunset",
    "falling in love":          "romantic scenic travel couple intimate private beautiful",
    "newly in love":            "romantic couple travel scenic private intimate beautiful",
    "newlywed":                 "honeymoon travel luxury romantic private resort beach scenic",
    "newlyweds":                "honeymoon couple romantic luxury private resort scenic",
    "just got married":         "honeymoon couple romantic luxury private resort scenic",
    "rekindling":               "romantic travel intimate private scenic couple quiet resort",
    "rekindling romance":       "romantic travel intimate private scenic couple quiet resort",
    "quality time":             "romantic travel private scenic couple intimate quiet peaceful",
    "quality time together":    "romantic couple travel private scenic intimate quiet peaceful",
    "just us":                  "private travel couple intimate scenic romantic secluded",
    "just the two of us":       "private couple travel intimate scenic romantic secluded",
    "together":                 "couple travel intimate private scenic romantic quiet",
    "soulmate":                 "romantic travel scenic luxury private couple intimate",
    "sweetheart":               "romantic travel intimate private couple scenic sunset",
    "newly engaged":            "romantic travel scenic viewpoint private couple luxury",
    "got engaged":              "romantic travel scenic viewpoint private couple luxury",
    "elopement":                "intimate travel private romantic scenic couple secluded",
    "romantic getaway":         "romantic couple travel private scenic intimate luxury",
    "couples retreat":          "couple retreat romantic private scenic intimate luxury",
    "love trip":                "romantic couple travel scenic private intimate",
    "romance":                  "romantic travel scenic couple private intimate beautiful",
    "affectionate":             "romantic travel intimate couple private scenic warm",
    "passionate":               "romantic travel couple intimate scenic private vibrant",
    "intimate":                 "intimate travel private couple romantic scenic quiet",
    "devoted":                  "romantic travel couple private scenic intimate resort",
    "smitten":                  "romantic travel scenic couple intimate private sunset",
    "lovesick":                 "romantic travel couple scenic private intimate beautiful",
}

# ═════════════════════════════════════════════════════════════
# E. CURIOSITY & LEARNING
# ═════════════════════════════════════════════════════════════
CURIOSITY: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "tò mò":                    "discovery exploration cultural local authentic learning",
    "tò mò lắm":                "discovery exploration cultural local learning curious",
    "rất tò mò":                "discovery exploration cultural local learning curious",
    "muốn học":                 "educational cultural heritage museum workshop local",
    "muốn học hỏi":             "educational cultural heritage museum workshop immersive",
    "hiểu thêm":                "cultural heritage history museum local authentic learning",
    "muốn hiểu":                "cultural heritage history museum local learning",
    "muốn hiểu hơn":            "cultural heritage history museum local learning discovery",
    "muốn biết":                "discovery cultural heritage educational learning authentic",
    "muốn biết thêm":           "discovery cultural heritage educational learning authentic",
    "trải nghiệm":              "new experience cultural authentic local immersive",
    "trải nghiệm mới":          "new experience cultural authentic local immersive discovery",
    "tìm kiếm trải nghiệm":     "new experience discovery cultural authentic local immersive",
    "khám phá":                 "exploration discovery adventure outdoor cultural new experience",
    "đi khám phá":              "exploration discovery adventure cultural new travel experience",
    "tìm hiểu":                 "discovery cultural learning heritage educational",
    "tìm tòi":                  "exploration discovery cultural adventure outdoor new",
    "ham học":                  "educational cultural museum workshop heritage tour learning",
    "ham học hỏi":              "educational cultural heritage museum workshop immersive",
    "yêu văn hóa":              "cultural heritage local tradition festival community",
    "yêu lịch sử":              "history heritage monument museum ancient educational",
    "yêu nghệ thuật":           "art gallery museum creative cultural exhibition",
    "mê nghệ thuật":            "art gallery museum creative cultural exhibition aesthetic",
    "đam mê đọc":               "literary heritage cultural intellectual book local",
    "cởi mở":                   "diverse cultural authentic open minded discovery",
    "học hỏi":                  "educational heritage cultural museum workshop local",
    "tiếp thu":                 "educational cultural heritage workshop immersive learning",
    "nghiên cứu":               "heritage museum cultural educational discovery authentic",
    "say mê":                   "passionate cultural art discovery heritage immersive",
    "thắc mắc":                 "discovery exploration cultural local learning curious",
    "tìm bản thân":             "self discovery solo nature peaceful scenic exploration",
    "tìm lại bản thân":         "self discovery solo nature peaceful scenic exploration",
    "tư duy":                   "intellectual cultural heritage educational discovery mindful",
    "thích học":                "educational cultural heritage museum workshop local",
    "thích tìm hiểu":           "discovery cultural learning heritage educational curious",

    # ── English ─────────────────────────────────────────────
    "curious":                  "discovery exploration cultural local learning new experience",
    "very curious":             "discovery exploration cultural local learning curious",
    "intellectual":             "museum heritage cultural art history educational",
    "to discover":              "discovery off beaten path hidden gem new experience",
    "want to discover":         "discovery cultural heritage new experience travel",
    "learner":                  "educational cultural workshop heritage immersive",
    "love learning":            "educational cultural heritage museum workshop immersive",
    "keen to learn":            "educational cultural heritage museum workshop learning",
    "inspiration":              "scenic cultural discovery art heritage beautiful",
    "looking for inspiration":  "scenic cultural discovery art heritage beautiful",
    "open minded":              "discovery cultural new experience diverse authentic",
    "open-minded":              "discovery cultural new experience diverse authentic",
    "exploration":              "exploration discovery outdoor adventure cultural new",
    "love culture":             "cultural heritage local tradition festival community",
    "love history":             "history heritage monument museum ancient educational",
    "love art":                 "art gallery museum creative cultural exhibition",
    "passionate about art":     "art gallery museum creative cultural exhibition aesthetic",
    "knowledge":                "educational cultural museum heritage learning workshop",
    "learning":                 "educational cultural heritage museum workshop immersive",
    "research":                 "heritage museum cultural educational discovery authentic",
    "mindful":                  "mindfulness meditation nature peaceful scenic retreat",
    "growth":                   "educational cultural discovery heritage authentic new",
    "self discovery":           "self discovery solo nature peaceful scenic exploration",
    "find myself":              "self discovery solo nature peaceful scenic exploration",
    "inquisitive":              "discovery exploration cultural local learning curious",
    "studious":                 "educational cultural heritage museum workshop immersive",
    "thoughtful":               "mindful cultural scenic nature peaceful discovery",
    "enlightened":              "cultural heritage educational discovery authentic local",
    "seeking":                  "exploration discovery cultural adventure outdoor new",
    "investigative":            "discovery exploration heritage educational authentic local",
    "bookish":                  "heritage cultural educational museum literary authentic",
    "academic":                 "educational heritage museum cultural scholarly discovery",
    "philosophical":            "mindful peaceful nature reflection cultural discovery",
    "wondering":                "discovery scenic exploration curious cultural new",
    "self aware":               "mindful self discovery peaceful nature reflection",
}

# ═════════════════════════════════════════════════════════════
# F. EXCITEMENT & THRILL
# ═════════════════════════════════════════════════════════════
EXCITEMENT: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "hứng khởi":                "adventure outdoor adrenaline sport active lively",
    "rất hứng khởi":            "adventure outdoor adrenaline sport active lively energetic",
    "hứng thú":                 "adventure outdoor active sport discovery stimulating",
    "mạo hiểm":                 "adventure adrenaline outdoor extreme sport trekking",
    "thích mạo hiểm":           "adventure adrenaline outdoor extreme sport trekking bold",
    "muốn mạo hiểm":            "adventure adrenaline outdoor extreme sport trekking bold",
    "thách thức":               "challenge sport outdoor adventure adrenaline extreme",
    "muốn thử thách":           "challenge sport outdoor adventure adrenaline extreme",
    "tìm thử thách":            "challenge sport outdoor adventure adrenaline extreme",
    "năng lượng":               "active outdoor adventure sport lively energetic",
    "tràn đầy năng lượng":      "very active outdoor adventure sport energetic lively",
    "cảm giác mạnh":            "adrenaline extreme sport adventure outdoor thrilling",
    "tìm cảm giác mạnh":        "adrenaline extreme sport adventure outdoor thrilling",
    "sẵn sàng":                 "flexible outdoor adventure active discovery sport",
    "muốn thử":                 "new experience adventure outdoor active sport discovery",
    "muốn thử cái mới":         "new experience adventure outdoor active discovery sport",
    "bứt phá":                  "extreme outdoor adrenaline challenge sport adventure",
    "mạnh mẽ":                  "active outdoor sport adventure energetic challenge",
    "tràn đầy":                 "vibrant energetic active outdoor sport adventure",
    "quyết tâm":                "challenge outdoor sport adventure bold active",
    "bùng cháy":                "adrenaline vibrant energetic active sport outdoor",
    "bùng nổ":                  "adrenaline vibrant energetic outdoor sport adventure",
    "cao hứng":                 "adventure outdoor adrenaline active energetic sport",
    "đam mê":                   "passionate adventure outdoor sport active discovery",
    "phấn khích":               "adventure lively active outdoor sport energetic",
    "nhiệt huyết":              "passionate active outdoor adventure sport energetic",
    "xung phong":               "bold active outdoor adventure sport adrenaline",
    "chinh phục":               "adventure outdoor summit challenge adrenaline sport",
    "muốn chinh phục":          "adventure outdoor summit challenge adrenaline sport",
    "gan lì":                   "bold outdoor adventure extreme tenacious sport",
    "hừng hực":                 "energetic active outdoor adrenaline sport adventure",
    "không sợ":                 "fearless bold outdoor adventure adrenaline sport",
    "lì lợm":                   "tenacious outdoor adventure bold sport challenge",

    # ── English ─────────────────────────────────────────────
    "excited":                  "adventure lively active outdoor sport adrenaline",
    "so excited":               "adventure lively active outdoor sport adrenaline",
    "really excited":           "adventure lively active outdoor sport adrenaline",
    "super excited":            "adventure lively active outdoor sport adrenaline",
    "pumped":                   "adrenaline adventure outdoor sport active energetic",
    "pumped up":                "adrenaline adventure outdoor sport active energetic",
    "hyped":                    "lively vibrant energetic outdoor adventure sport",
    "thrill seeking":           "adrenaline extreme sport adventure outdoor thrilling",
    "thrill-seeking":           "adrenaline extreme sport adventure outdoor thrilling",
    "thrill seeker":            "adrenaline extreme sport adventure outdoor thrilling",
    "adrenaline junkie":        "adrenaline extreme sport adventure outdoor thrilling",
    "energetic":                "active outdoor sport adventure lively energetic",
    "full of energy":           "active outdoor sport adventure lively energetic",
    "bold":                     "adventure outdoor bold exploration off beaten path",
    "daring":                   "adventure bold outdoor extreme adrenaline sport",
    "fearless":                 "adventure bold extreme outdoor adrenaline sport",
    "brave":                    "adventure bold outdoor extreme sport adrenaline",
    "push limits":              "extreme sport adventure adrenaline challenge outdoor",
    "push my limits":           "extreme sport adventure adrenaline challenge outdoor",
    "feel alive":               "adventure outdoor active adrenaline scenic stimulating",
    "want to feel alive":       "adventure outdoor active adrenaline scenic stimulating",
    "adrenaline":               "adrenaline extreme sport adventure outdoor thrilling",
    "adrenaline rush":          "adrenaline extreme sport adventure outdoor thrilling",
    "wild":                     "adventure wild outdoor remote extreme nature",
    "fired up":                 "active outdoor energetic adventure sport adrenaline",
    "go-getter":                "active outdoor adventure flexible sport discovery",
    "unstoppable":              "active outdoor bold adventure sport adrenaline",
    "ready for anything":       "flexible outdoor adventure active discovery sport",
    "seek adventure":           "adventure trekking outdoor adrenaline sport exploration",
    "live on the edge":         "adrenaline extreme sport adventure outdoor thrilling",
    "bucket list":              "adventure bucket list unique experience outdoor exploration",
    "bucket list trip":         "adventure bucket list unique experience outdoor exploration",
    "once in a lifetime":       "unique adventure experience bucket list outdoor exploration",
    "challenge myself":         "challenge sport outdoor adventure adrenaline extreme",
    "challenge":                "challenge sport outdoor adventure adrenaline extreme",
    "thrill":                   "thrill adrenaline extreme sport adventure outdoor",
    "epic":                     "epic adventure outdoor scenic dramatic adrenaline exploration",
    "epic trip":                "epic adventure outdoor scenic dramatic exploration adrenaline",
    "unforgettable":            "unique unforgettable adventure experience outdoor scenic",
}

# ═════════════════════════════════════════════════════════════
# G. NOSTALGIA & HERITAGE
# ═════════════════════════════════════════════════════════════
NOSTALGIA: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "hoài cổ":                  "heritage historic vintage traditional old town atmosphere",
    "rất hoài cổ":              "very nostalgic heritage vintage traditional old town",
    "thích hoài cổ":            "nostalgic heritage vintage traditional old town atmosphere",
    "hoài niệm":                "nostalgic heritage scenic beautiful traditional atmospheric",
    "nhớ ngày xưa":             "nostalgic heritage vintage traditional old world sentimental",
    "nhớ lại":                  "nostalgic heritage scenic beautiful traditional peaceful",
    "thương nhớ":               "nostalgic scenic beautiful peaceful gentle heritage",
    "ký ức":                    "nostalgic heritage scenic beautiful peaceful traditional",
    "về nguồn":                 "cultural roots heritage traditional local authentic",
    "tìm về nguồn cội":         "cultural roots heritage local authentic traditional community",
    "bản sắc":                  "cultural identity heritage local authentic traditional",
    "truyền thống":             "traditional heritage cultural local craft festival",
    "văn hóa truyền thống":     "traditional cultural heritage local craft festival authentic",
    "tìm gốc":                  "cultural roots heritage local authentic community",
    "cội nguồn":                "cultural roots heritage local authentic traditional",
    "cổ xưa":                   "heritage ancient historic traditional atmosphere vintage",
    "hương xưa":                "heritage vintage nostalgic atmospheric old town scenic",
    "thời xưa":                 "historic vintage traditional heritage atmosphere cultural",
    "quá khứ":                  "heritage nostalgia historic traditional old town museum",
    "di sản":                   "heritage historic ancient monument museum cultural",
    "dân gian":                 "folk culture heritage traditional local authentic craft",
    "lịch sử":                  "history heritage monument ancient museum educational",
    "tiền nhân":                "ancestral heritage cultural roots traditional authentic",
    "nhớ quê":                  "nostalgic rural countryside local familiar cozy heritage",
    "nhớ quê hương":            "nostalgic hometown rural countryside local familiar heritage",
    "cổ điển":                  "heritage classic traditional atmospheric vintage cultural",
    "xưa cũ":                   "vintage heritage atmospheric traditional old town historic",

    # ── English ─────────────────────────────────────────────
    "nostalgic":                "heritage nostalgia vintage traditional historic atmosphere",
    "feeling nostalgic":        "heritage nostalgia vintage traditional historic atmosphere",
    "sentimental":              "heritage nostalgic scenic beautiful peaceful traditional",
    "old soul":                 "heritage historic traditional atmospheric vintage old town",
    "old town":                 "old town heritage cobblestone charming historic atmospheric",
    "love old towns":           "old town heritage cobblestone charming historic atmospheric",
    "roots trip":               "cultural roots heritage local authentic community",
    "find my roots":            "cultural roots heritage local authentic traditional community",
    "ancestral":                "ancestral heritage cultural roots traditional authentic",
    "vintage":                  "vintage heritage atmospheric old town traditional charm",
    "love vintage":             "vintage heritage atmospheric old town traditional charm",
    "historical":               "historical heritage monument ancient museum educational",
    "love history":             "history heritage monument ancient museum educational",
    "history lover":            "history heritage monument ancient museum educational",
    "timeless":                 "heritage scenic beautiful traditional cultural peaceful",
    "classic":                  "classic heritage traditional scenic cultural historic",
    "antique":                  "heritage vintage antique old town atmospheric traditional",
    "ancient":                  "ancient heritage historic monument museum cultural",
    "preserved":                "heritage conservation historic traditional authentic cultural",
    "time capsule":             "heritage vintage nostalgic atmospheric old town traditional",
    "step back in time":        "heritage historic vintage traditional old town atmospheric",
    "retro":                    "vintage heritage atmospheric old town traditional charm",
    "old world":                "heritage traditional atmospheric vintage charming old town",
    "old-world":                "heritage traditional atmospheric vintage charming old town",
    "reminiscing":              "nostalgic heritage scenic traditional beautiful peaceful",
    "wistful":                  "nostalgic scenic beautiful peaceful traditional heritage",
    "bygone":                   "heritage historic traditional atmospheric vintage old town",
    "olden":                    "heritage historic traditional old town atmospheric vintage",
    "storied":                  "heritage historic scenic cultural traditional beautiful",
    "legendary":                "heritage scenic historic iconic cultural traditional",
}

# ═════════════════════════════════════════════════════════════
# H. SOCIAL FATIGUE
# ═════════════════════════════════════════════════════════════
SOCIAL_FATIGUE: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "mệt xã hội":               "solo quiet secluded nature peaceful off grid retreat",
    "mệt với người":            "solo quiet secluded nature peaceful off grid retreat",
    "ngại giao tiếp":           "solo quiet peaceful secluded nature gentle off grid",
    "ngại tiếp xúc":            "solo quiet peaceful secluded nature gentle",
    "cần không gian":           "spacious open nature quiet secluded peaceful",
    "cần không gian riêng":     "private spacious open nature quiet secluded peaceful",
    "né đám đông":              "secluded quiet off beaten path peaceful remote nature",
    "tránh đám đông":           "remote peaceful off beaten path secluded quiet nature",
    "sợ đám đông":              "secluded remote quiet nature peaceful off grid",
    "ghét ồn":                  "quiet peaceful secluded nature tranquil off grid",
    "ghét đông người":          "secluded quiet off beaten path peaceful remote nature",
    "cần yên tĩnh":             "quiet peaceful tranquil secluded nature retreat",
    "cần yên":                  "quiet peaceful tranquil secluded nature retreat",
    "muốn yên tĩnh":            "quiet peaceful tranquil secluded nature retreat",
    "thích yên tĩnh":           "quiet peaceful tranquil secluded nature gentle travel",
    "thích vắng":               "secluded quiet remote nature peaceful off grid",
    "muốn vắng":                "secluded remote quiet nature peaceful off grid",
    "nội tâm":                  "solo introspective peaceful nature quiet reflection",
    "hướng nội":                "solo quiet secluded nature peaceful introspective",
    "suy nghĩ":                 "solo peaceful quiet nature meditation reflection",
    "muốn suy nghĩ":            "solo peaceful quiet nature meditation reflection",
    "cần tĩnh tâm":             "meditation retreat peaceful nature quiet mindfulness",
    "muốn tĩnh tâm":            "meditation retreat peaceful nature quiet mindfulness",
    "muốn riêng":               "private secluded solo quiet nature off grid",
    "cần riêng":                "private secluded solo quiet nature off grid",
    "muốn riêng tư":            "private secluded solo quiet nature off grid",
    "tránh ồn":                 "quiet peaceful nature secluded tranquil off grid",
    "cần im lặng":              "quiet silent peaceful nature secluded retreat",
    "thích im lặng":            "quiet silent peaceful nature secluded retreat",
    "cần nghỉ xã hội":          "retreat quiet nature secluded solo off grid",

    # ── English ─────────────────────────────────────────────
    "introverted":              "solo quiet secluded nature peaceful gentle off grid",
    "introvert":                "solo quiet secluded nature peaceful gentle off grid",
    "socially exhausted":       "solo quiet secluded nature peaceful off grid retreat",
    "social fatigue":           "solo quiet secluded nature peaceful off grid retreat",
    "people fatigue":           "solo quiet secluded nature peaceful off grid retreat",
    "need space":               "open spacious nature quiet secluded peaceful",
    "need my space":            "open spacious nature quiet secluded peaceful",
    "need alone time":          "solo quiet secluded nature peaceful reflection",
    "alone time":               "solo quiet secluded nature peaceful reflection",
    "avoid crowds":             "secluded quiet off beaten path remote peaceful",
    "hate crowds":              "secluded quiet remote nature peaceful off beaten path",
    "no crowds":                "secluded quiet remote nature peaceful off beaten path",
    "quiet retreat":            "retreat quiet peaceful nature secluded wellness meditation",
    "need quiet":               "quiet peaceful tranquil secluded nature serene",
    "need silence":             "quiet silent peaceful nature secluded retreat",
    "need solitude":            "solo secluded quiet nature peaceful retreat meditation",
    "solitude":                 "solo secluded quiet nature peaceful retreat",
    "craving solitude":         "solo secluded quiet nature peaceful retreat meditation",
    "contemplative":            "peaceful quiet scenic nature meditation reflection solo",
    "withdrawn":                "solo quiet peaceful secluded nature gentle retreat",
    "reclusive":                "solo secluded quiet off grid nature peaceful",
    "antisocial":               "solo remote secluded quiet nature off grid",
    "private":                  "private secluded solo quiet nature exclusive",
    "self-reliant":             "solo independent flexible discovery nature peaceful",
    "off-grid":                 "off grid remote secluded nature quiet peaceful",
    "off grid":                 "off grid remote secluded nature quiet peaceful",
    "digital detox":            "digital detox off grid nature quiet secluded peaceful",
    "unplug":                   "off grid nature quiet secluded peaceful digital detox",
    "disconnect":               "off grid nature quiet secluded peaceful digital detox",
    "low-key":                  "quiet peaceful gentle secluded nature relaxed",
    "low key":                  "quiet peaceful gentle secluded nature relaxed",
    "me time":                  "solo quiet nature peaceful reflection secluded",
    "quiet time":               "peaceful quiet nature secluded retreat gentle",
    "off radar":                "remote secluded off grid quiet nature peaceful",
    "reserved":                 "solo quiet secluded nature peaceful gentle",
    "hermit":                   "remote secluded off grid quiet nature solo",
    "detached":                 "solo quiet secluded nature peaceful off grid",
    "shy":                      "solo quiet gentle peaceful secluded nature",
}

# ═════════════════════════════════════════════════════════════
# I. JOY & CELEBRATION
# ═════════════════════════════════════════════════════════════
JOY_CELEBRATION: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "vui vẻ":                   "fun joyful lively social entertainment activities vibrant",
    "rất vui":                  "very fun joyful lively social entertainment activities",
    "vui lắm":                  "very fun joyful lively social entertainment vibrant",
    "hạnh phúc":                "happy joyful scenic beautiful resort luxury peaceful",
    "rất hạnh phúc":            "very happy joyful scenic beautiful resort luxury peaceful",
    "phấn khởi":                "lively joyful fun social activities entertainment vibrant",
    "hân hoan":                 "joyful festive lively social celebration activities",
    "hào hứng":                 "enthusiastic adventure active fun discovery lively",
    "muốn ăn mừng":             "celebration travel festive social entertainment party lively",
    "ăn mừng":                  "celebration festive social entertainment party lively",
    "kỷ niệm đáng nhớ":         "memorable celebration travel special scenic luxury",
    "sinh nhật":                "birthday celebration travel special scenic fun social",
    "mừng sinh nhật":           "birthday celebration travel special scenic fun social",
    "tốt nghiệp":               "graduation celebration travel achievement special scenic fun",
    "mừng tốt nghiệp":          "graduation celebration travel achievement special scenic",
    "thăng chức":               "promotion celebration travel achievement special scenic",
    "lễ kỷ niệm":               "anniversary celebration travel special scenic luxury",
    "tổ chức":                  "celebration organized travel social event special",
    "bữa tiệc":                 "party celebration social lively entertainment fun travel",
    "tiệc":                     "party social lively entertainment fun celebration",
    "dịp vui":                  "joyful occasion celebration travel fun social",
    "niềm vui":                 "joy fun joyful travel scenic beautiful social",

    # ── English ─────────────────────────────────────────────
    "happy":                    "happy joyful scenic beautiful resort peaceful",
    "very happy":               "very happy joyful scenic beautiful resort luxury peaceful",
    "feeling happy":            "happy joyful scenic beautiful resort peaceful",
    "joyful":                   "joyful fun lively social entertainment activities",
    "celebrating":              "celebration festive social entertainment party lively",
    "celebration":              "celebration travel festive social entertainment lively",
    "celebrate":                "celebrate travel festive social entertainment lively",
    "birthday trip":            "birthday celebration travel special scenic fun social",
    "birthday":                 "birthday celebration travel special scenic fun social",
    "birthday celebration":     "birthday celebration travel special scenic fun",
    "graduation":               "graduation celebration travel achievement special scenic",
    "graduation trip":          "graduation celebration travel achievement special scenic",
    "promotion":                "promotion celebration travel achievement special scenic",
    "good news":                "celebration travel festive joyful special scenic",
    "milestone":                "milestone celebration travel special scenic achievement",
    "achievement":              "achievement celebration travel special scenic",
    "rewarding myself":         "luxury treat celebration travel resort spa premium",
    "treat myself":             "luxury treat celebration travel resort spa premium",
    "spoil myself":             "luxury treat celebration travel resort spa premium",
    "girls night out":          "social celebration lively entertainment fun nightlife",
    "bachelorette party":       "celebration party social lively entertainment fun",
    "bachelor party":           "celebration party social lively adventure entertainment fun",
    "reunion":                  "reunion celebration social friends family warm lively",
    "family reunion":           "family reunion celebration social warm bonding lively",
    "hen party":                "celebration party social lively entertainment fun",
    "stag do":                  "celebration party social adventure lively entertainment",
    "party":                    "party social lively entertainment fun celebration",
    "festival":                 "festival celebration cultural lively entertainment crowd",
    "excitement":               "exciting lively adventure fun social vibrant",
    "positive":                 "positive uplifting joyful scenic beautiful travel",
    "great mood":               "joyful positive lively fun social activities entertainment",
}

# ═════════════════════════════════════════════════════════════
# J. FREEDOM & ESCAPE
# ═════════════════════════════════════════════════════════════
FREEDOM_ESCAPE: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "tự do":                    "freedom travel flexible independent open road exploration",
    "muốn tự do":               "freedom travel flexible independent open road exploration",
    "cảm giác tự do":           "freedom travel open outdoor flexible independent scenic",
    "bay nhảy":                 "freedom flexible open travel adventure exploration",
    "không ràng buộc":          "free flexible independent travel open exploration",
    "không bị ràng buộc":       "free flexible independent travel open exploration",
    "buông bỏ":                 "let go freedom travel peaceful nature open scenic",
    "thoải mái":                "free relaxed comfortable flexible travel",
    "phóng khoáng":             "free spirited open travel adventure flexible exploration",
    "lang thang":               "wandering free flexible travel exploration open road",
    "rong ruổi":                "roaming road trip flexible travel adventure open",
    "phiêu bạt":                "wandering travel flexible adventure open exploration",
    "đi đâu cũng được":         "anywhere flexible open travel destination",
    "không có kế hoạch":        "spontaneous unplanned flexible travel adventure open",
    "không cần kế hoạch":       "spontaneous unplanned flexible travel adventure open",
    "tùy hứng":                 "spontaneous flexible travel open adventure",
    "đột xuất":                 "spontaneous impromptu flexible travel open adventure",
    "theo gió":                 "free spontaneous travel flexible open adventure",
    "đường dài":                "road trip long drive scenic freedom open travel",
    "lái xe dài":               "road trip long drive scenic freedom open travel",
    "phượt":                    "road trip backpacker flexible adventure open freedom",
    "đi phượt":                 "road trip backpacker flexible adventure open freedom",
    "chuyến phượt":             "road trip backpacker flexible adventure open freedom",

    # ── English ─────────────────────────────────────────────
    "free":                     "freedom travel flexible open independent exploration",
    "freedom":                  "freedom travel flexible independent open road",
    "feel free":                "freedom travel flexible open independent scenic",
    "craving freedom":          "freedom travel flexible open independent exploration",
    "no plans":                 "spontaneous unplanned flexible travel open adventure",
    "no itinerary":             "spontaneous flexible unplanned travel open adventure",
    "spontaneous":              "spontaneous flexible travel open adventure exploration",
    "impromptu":                "impromptu spontaneous flexible travel adventure",
    "impulsive":                "spontaneous impulsive flexible travel open adventure",
    "wander":                   "wandering free flexible travel exploration open",
    "wanderlust":               "wanderlust travel exploration adventure discovery open",
    "road trip":                "road trip scenic drive flexible freedom open travel",
    "open road":                "open road road trip scenic drive freedom travel",
    "hit the road":             "road trip drive freedom scenic travel open",
    "just drive":               "road trip drive freedom scenic travel",
    "pack my bags":             "travel adventure exploration freedom getaway",
    "just go":                  "spontaneous travel adventure freedom flexible",
    "take off":                 "spontaneous travel adventure freedom getaway",
    "no ties":                  "freedom flexible independent travel open exploration",
    "escape routine":           "escape freedom travel new experience open adventure",
    "escape the city":          "escape city travel nature peaceful open freedom",
    "escape the noise":         "escape noise travel nature quiet peaceful freedom",
    "change of scenery":        "new scenery travel open freedom discovery exploration",
    "fresh start":              "fresh start travel freedom open new experience",
    "new chapter":              "new chapter travel freedom open adventure discovery",
    "unwind":                   "unwind travel relax peaceful nature freedom",
    "detach":                   "detach freedom travel nature quiet peaceful off grid",
    "roam":                     "roam travel freedom flexible open adventure",
    "roaming":                  "roaming travel freedom flexible open adventure",
    "nomadic":                  "nomadic travel freedom flexible open road",
    "backpack":                 "backpack travel freedom flexible budget adventure",
    "backpacking":              "backpacking travel freedom flexible budget adventure",
    "unplugged":                "unplugged off grid freedom nature quiet peaceful",
    "off the grid":             "off grid freedom nature quiet peaceful secluded",
    "off-the-grid":             "off grid freedom nature quiet peaceful secluded",
}

# ═════════════════════════════════════════════════════════════
# K. SPIRITUAL & MINDFULNESS
# ═════════════════════════════════════════════════════════════
SPIRITUAL_MINDFULNESS: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "tâm linh":                 "spiritual sacred pilgrimage temple peaceful mindfulness",
    "tâm linh sâu sắc":         "deep spiritual sacred pilgrimage temple mindfulness",
    "tìm sự bình an":           "peaceful spiritual mindfulness nature serene retreat",
    "bình an":                  "peaceful spiritual nature mindfulness serene retreat",
    "bình an nội tâm":          "inner peace spiritual mindfulness nature serene retreat",
    "nội tâm":                  "inner spiritual mindfulness peaceful nature reflection",
    "tĩnh tâm":                 "mindfulness meditation peaceful spiritual nature retreat",
    "thiền định":               "meditation mindfulness spiritual peaceful retreat nature",
    "thiền":                    "meditation mindfulness spiritual peaceful retreat nature",
    "cầu nguyện":               "prayer spiritual pilgrimage temple sacred peaceful",
    "hành hương":               "pilgrimage spiritual sacred temple heritage holy",
    "đi hành hương":            "pilgrimage spiritual sacred temple heritage holy",
    "lễ chùa":                  "temple Buddhist sacred spiritual peaceful heritage",
    "thờ phụng":                "sacred spiritual worship temple pilgrimage heritage",
    "kết nối với thiên nhiên":  "connect nature spiritual peaceful mindfulness outdoor",
    "hòa mình":                 "immerse nature spiritual peaceful mindfulness outdoor",
    "hòa hợp":                  "harmony spiritual nature peaceful mindfulness balance",
    "cân bằng tâm hồn":         "soul balance spiritual mindfulness peaceful nature",
    "chữa lành tâm hồn":        "soul healing spiritual wellness mindfulness peaceful nature",
    "nâng cao tinh thần":       "uplift spirit spiritual wellness mindfulness peaceful",
    "ý nghĩa":                  "meaningful spiritual authentic cultural nature discovery",
    "sâu sắc":                  "deep meaningful spiritual authentic cultural nature",
    "trải nghiệm ý nghĩa":      "meaningful spiritual authentic experience cultural nature",
    "sống chậm":                "slow living mindfulness peaceful nature spiritual wellness",
    "sống đơn giản":            "simple living mindfulness peaceful nature spiritual",
    "gần gũi thiên nhiên":      "close to nature spiritual peaceful mindfulness outdoor",
    "kết nối với bản thân":     "self connection spiritual mindfulness peaceful nature",

    # ── English ─────────────────────────────────────────────
    "spiritual":                "spiritual sacred pilgrimage temple peaceful mindfulness",
    "spirituality":             "spiritual sacred pilgrimage temple peaceful mindfulness",
    "spiritual journey":        "spiritual journey pilgrimage sacred temple peaceful",
    "spiritual travel":         "spiritual travel sacred pilgrimage temple mindfulness",
    "finding peace":            "peaceful spiritual nature mindfulness serene retreat",
    "inner peace":              "inner peace spiritual mindfulness nature serene retreat",
    "peace of mind":            "peace of mind spiritual nature mindfulness serene",
    "mindfulness":              "mindfulness meditation spiritual peaceful nature retreat",
    "mindful":                  "mindful spiritual meditation peaceful nature retreat",
    "meditation":               "meditation mindfulness spiritual peaceful retreat nature",
    "meditate":                 "meditation mindfulness spiritual peaceful retreat nature",
    "pilgrimage":               "pilgrimage spiritual sacred temple heritage holy",
    "sacred":                   "sacred spiritual pilgrimage temple heritage holy peaceful",
    "holy":                     "holy spiritual sacred pilgrimage temple peaceful",
    "temple visit":             "temple spiritual sacred peaceful heritage mindfulness",
    "yoga":                     "yoga spiritual mindfulness wellness peaceful retreat nature",
    "yoga retreat":             "yoga retreat spiritual mindfulness wellness peaceful nature",
    "retreat":                  "retreat spiritual mindfulness peaceful nature wellness",
    "silent retreat":           "silent retreat meditation spiritual peaceful nature",
    "vipassana":                "vipassana meditation spiritual silent retreat peaceful",
    "meaningful":               "meaningful spiritual authentic cultural nature discovery",
    "purpose":                  "purposeful meaningful spiritual authentic cultural",
    "self reflection":          "self reflection spiritual mindfulness peaceful nature",
    "reflect":                  "reflection spiritual mindfulness peaceful nature",
    "gratitude":                "grateful meaningful spiritual scenic beautiful nature",
    "slow living":              "slow living mindfulness peaceful nature spiritual wellness",
    "simple life":              "simple mindful peaceful nature spiritual wellness",
    "connect with nature":      "connect nature spiritual peaceful mindfulness outdoor",
    "grounding":                "grounding spiritual nature peaceful mindfulness outdoor",
    "healing energy":           "healing energy spiritual wellness nature peaceful",
    "zen":                      "zen peaceful spiritual mindfulness nature serene",
    "holistic":                 "holistic wellness spiritual mindfulness nature peaceful",
    "soul searching":           "soul searching spiritual mindfulness peaceful nature",
    "soul journey":             "soul journey spiritual mindfulness peaceful nature",
}

# ═════════════════════════════════════════════════════════════
# L. FAMILY LOVE & BONDING
# ═════════════════════════════════════════════════════════════
FAMILY_BONDING: dict[str, str] = {
    # ── Vietnamese ──────────────────────────────────────────
    "yêu gia đình":             "family love bonding warm togetherness travel comfortable",
    "vì gia đình":              "family love bonding warm togetherness travel comfortable",
    "cùng gia đình":            "family travel bonding warm togetherness comfortable",
    "gắn kết gia đình":         "family bonding warm love togetherness comfortable travel",
    "kỷ niệm gia đình":         "family memories bonding warm love togetherness travel",
    "thời gian bên gia đình":   "family time bonding warm love togetherness travel",
    "muốn dành thời gian":      "quality time family bonding warm togetherness",
    "dành thời gian cho nhau":  "quality time family couple bonding warm togetherness",
    "tụ họp gia đình":          "family reunion gathering bonding warm love",
    "tụ họp":                   "reunion gathering social bonding warm love community",
    "đi cùng con":              "family children travel bonding warm love education",
    "đưa con đi":               "family children travel bonding warm fun education",
    "cho con trải nghiệm":      "family children educational travel experience fun bonding",
    "trẻ em thích":             "family kids fun activities safe educational travel",
    "con trẻ vui":              "family kids fun activities safe educational travel",
    "ba mẹ và con":             "family parents children travel bonding warm love",
    "ông bà và cháu":           "multigenerational family travel bonding warm heritage gentle",
    "cha mẹ":                   "family parents comfortable scenic cultural bonding warm",
    "cùng cha mẹ":              "family parents comfortable scenic cultural bonding warm",
    "thăm bố mẹ":               "family parents visit bonding warm comfortable cultural",
    "thăm ông bà":              "family grandparents visit bonding warm gentle heritage",
    "chăm sóc gia đình":        "family care bonding warm comfortable gentle travel",
    "yêu thương":               "love warm bonding family couple scenic beautiful",
    "trân trọng":               "cherish meaningful bonding family scenic beautiful",

    # ── English ─────────────────────────────────────────────
    "family time":              "family time bonding warm love togetherness travel",
    "quality family time":      "quality family time bonding warm love togetherness",
    "family bonding":           "family bonding warm love togetherness comfortable travel",
    "bond with family":         "family bonding warm love togetherness comfortable",
    "spend time with family":   "family time bonding warm love togetherness travel",
    "family memories":          "family memories bonding warm love togetherness travel",
    "make memories":            "memorable family travel bonding warm love scenic",
    "create memories":          "memorable family travel bonding warm love scenic",
    "for the kids":             "family kids fun safe educational activities travel",
    "for my kids":              "family kids fun safe educational activities travel",
    "take kids":                "family kids fun safe educational activities travel",
    "children":                 "family children fun safe educational activities travel",
    "kids":                     "family kids fun safe activities travel bonding",
    "with my children":         "family children travel bonding warm love educational",
    "for my family":            "family travel bonding warm love comfortable scenic",
    "family vacation":          "family vacation travel bonding warm love comfortable",
    "family trip":              "family trip travel bonding warm love comfortable",
    "family holiday":           "family holiday travel bonding warm love comfortable",
    "togetherness":             "togetherness family bonding warm love comfortable scenic",
    "together as a family":     "family togetherness bonding warm love comfortable scenic",
    "whole family":             "whole family travel bonding warm love comfortable",
    "all of us":                "family travel togetherness bonding warm love comfortable",
    "close to family":          "family bonding warm love comfortable scenic community",
    "reunite":                  "reunion family friends bonding warm love social",
    "reconnect":                "reconnect family friends bonding warm love social",
    "reconnect with family":    "family reconnect bonding warm love togetherness",
    "spend time together":      "quality time family couple bonding warm togetherness",
    "parents":                  "family parents comfortable scenic cultural bonding warm",
    "visit parents":            "family parents visit bonding warm comfortable scenic",
    "see my parents":           "family parents visit bonding warm comfortable scenic",
}

# ═════════════════════════════════════════════════════════════
# MASTER REGISTRY
# ═════════════════════════════════════════════════════════════
ALL_EMOTIONS: dict[str, str] = {
    **EXHAUSTION_STRESS,
    **BOREDOM,
    **SADNESS,
    **ROMANCE,
    **CURIOSITY,
    **EXCITEMENT,
    **NOSTALGIA,
    **SOCIAL_FATIGUE,
    **JOY_CELEBRATION,
    **FREEDOM_ESCAPE,
    **SPIRITUAL_MINDFULNESS,
    **FAMILY_BONDING,
}